package com.dogancaglar.paymentservice.adapter.outbound.persistence.mybatis

import com.dogancaglar.paymentservice.adapter.outbound.persistence.entity.JournalEntryEntity
import com.dogancaglar.paymentservice.adapter.outbound.persistence.entity.LedgerEntryEntity
import com.dogancaglar.paymentservice.adapter.outbound.persistence.entity.PostingEntity
import com.dogancaglar.paymentservice.domain.model.ledger.LedgerEntry
import com.dogancaglar.paymentservice.domain.model.ledger.Posting

  internal object LedgerPersistenceMapper {

    fun toLedgerEntryEntity(entry: LedgerEntry): LedgerEntryEntity =
        LedgerEntryEntity(
            id = null, // Will be auto-generated by database
            journalId = entry.journalEntry.id,
            createdAt = entry.createdAt
        )

    fun toJournalEntryEntity(entry: LedgerEntry): JournalEntryEntity =
        JournalEntryEntity(
            id = entry.journalEntry.id,
            txType = entry.journalEntry.txType.name,
            name = entry.journalEntry.name,
            referenceType = entry.journalEntry.referenceType,
            referenceId = entry.journalEntry.referenceId,
            createdAt = entry.createdAt
        )

    fun toPostingEntities(entry: LedgerEntry): List<PostingEntity> =
        entry.journalEntry.postings.map { posting ->
            PostingEntity(
                journalId = entry.journalEntry.id,
                accountCode = posting.account.accountCode,
                accountType = posting.account.type.name,
                amount = posting.amount.quantity,
                direction = when (posting) {
                    is Posting.Debit -> "DEBIT"
                    is Posting.Credit -> "CREDIT"
                },
                currency = posting.amount.currency.currencyCode,
                createdAt = entry.createdAt
            )
        }
}