apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka-broker
          image:
            confluentinc/cp-server:latest
          env:
            - name: LOG_DIR
              value: /var/tmp
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: KAFKA_PROCESS_ROLES
              value: "broker"
            - name: LOG_DIR
              value: /var/tmp
          ports:
            - containerPort: 9092
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 6
          startupProbe:
            exec:
              command:
                - sh
                - -c
                - >
                  [[ "$(kafka-broker-api-versions --bootstrap-server localhost:9092 | grep 9092 | wc -l)" == "3" ]] || { echo >&2 "Broker count is not 3"; exit 1; } && [[ "$(curl -s kafka-controller-headless.my-namespace:9102/metrics | grep kafka_controller_kafkacontroller_preferredreplicaimbalancecount | tail -n 1 | grep -o '[^ ]\+$')" == "0.0" ]] || { echo >&2 "Replica Imbalance not 0"; exit 1; }
            failureThreshold: 60
            periodSeconds: 10
            initialDelaySeconds: 10
          volumes:
            - name: kafka-data
              persistentVolumeClaim:
                claimName: kafka-pvc
          workingDir: /var/tmp
          securityContext:
            fsGroup: 1000    # default to appuser -- must be overridden on RHOCP
            runAsUser: 1000    # default to appuser -- must be overridden on RHOCP
          resources:
            requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "2Gi"