apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-platform-config
  namespace: {{.Release.Namespace}}
data:
  KEYCLOAK_ISSUER_URL: {{.Values.KEYCLOAK_ISSUER_URL | quote}}
  EDGE_DB_URL: {{.Values.EDGE_DB_URL | quote}}
  CENTRAL_DB_URL: {{.Values.CENTRAL_DB_URL | quote}}
  EDGE_DB_NAME: {{.Values.EDGE_DB_NAME | quote}}
  CENTRAL_DB_NAME: {{.Values.CENTRAL_DB_NAME | quote}}
  YUGABYTE_DB_URL: {{.Values.YUGABYTE_DB_URL | quote}}
  # ...more keys as needed
