apiVersion: v1
kind: Secret
metadata:
  name: edge-db-credentials
  namespace: {{.Release.Namespace}}
type: Opaque
stringData:
  EDGE_DB_PAYMENT_SERVICE_USERNAME: {{.Values.EDGE_DB_PAYMENT_SERVICE_USERNAME | quote}}
  EDGE_DB_PAYMENT_SERVICE_PASSWORD: {{.Values.EDGE_DB_PAYMENT_SERVICE_PASSWORD | quote}}
  EDGE_DB_PAYMENT_EDGE_WORKERS_USERNAME: {{.Values.EDGE_DB_PAYMENT_EDGE_WORKERS_USERNAME | quote}}
  EDGE_DB_PAYMENT_EDGE_WORKERS_PASSWORD: {{.Values.EDGE_DB_PAYMENT_EDGE_WORKERS_PASSWORD | quote}}

  EDGE_DB_DUTY_USERNAME: {{.Values.EDGE_DB_DUTY_USERNAME | quote}}
  EDGE_DB_DUTY_PASSWORD: {{.Values.EDGE_DB_DUTY_PASSWORD | quote}}
  EDGE_DB_POSTGRES_PASSWORD: {{.Values.EDGE_DB_POSTGRES_PASSWORD | quote}}

---
apiVersion: v1
kind: Secret
metadata:
  name: central-db-credentials
  namespace: {{.Release.Namespace}}
type: Opaque
stringData:
  CENTRAL_DB_PAYMENT_CONSUMERS_USERNAME: {{.Values.CENTRAL_DB_PAYMENT_CONSUMERS_USERNAME | quote}}
  CENTRAL_DB_PAYMENT_CONSUMERS_PASSWORD: {{.Values.CENTRAL_DB_PAYMENT_CONSUMERS_PASSWORD | quote}}
  CENTRAL_DB_PAYMENT_CENTRAL_RELAY_USERNAME: {{.Values.CENTRAL_DB_PAYMENT_CENTRAL_RELAY_USERNAME | quote}}
  CENTRAL_DB_PAYMENT_CENTRAL_RELAY_PASSWORD: {{.Values.CENTRAL_DB_PAYMENT_CENTRAL_RELAY_PASSWORD | quote}}
  CENTRAL_DB_PAYMENT_EDGE_WORKERS_USERNAME: {{.Values.CENTRAL_DB_PAYMENT_EDGE_WORKERS_USERNAME | quote}}
  CENTRAL_DB_PAYMENT_EDGE_WORKERS_PASSWORD: {{.Values.CENTRAL_DB_PAYMENT_EDGE_WORKERS_PASSWORD | quote}}

  CENTRAL_DB_DUTY_USERNAME: {{.Values.CENTRAL_DB_DUTY_USERNAME | quote}}
  CENTRAL_DB_DUTY_PASSWORD: {{.Values.CENTRAL_DB_DUTY_PASSWORD | quote}}
  CENTRAL_DB_POSTGRES_PASSWORD: {{.Values.CENTRAL_DB_POSTGRES_PASSWORD | quote}}
---
apiVersion: v1
kind: Secret
metadata:
  name: kafka-credentials
  namespace: {{.Release.Namespace}}
type: Opaque
stringData:
  KAFKA_CLIENT_PASSWORD: {{.Values.KAFKA_CLIENT_PASSWORD | quote}}