apiVersion: v1
kind: Secret
metadata:
  name: payment-db-credentials
  namespace: {{.Release.Namespace}}
type: Opaque
stringData:
  PAYMENT_SERVICE_APP_DB_USER: {{.Values.PAYMENT_SERVICE_APP_DB_USER | quote}}
  PAYMENT_SERVICE_APP_DB_PASSWORD: {{.Values.PAYMENT_SERVICE_APP_DB_PASSWORD | quote}}
  PAYMENT_CONSUMERS_APP_DB_USER: {{.Values.PAYMENT_CONSUMERS_APP_DB_USER | quote}}
  PAYMENT_CONSUMERS_APP_DB_PASSWORD: {{.Values.PAYMENT_CONSUMERS_APP_DB_PASSWORD | quote}}
  ADMIN_POSTGRES_PASSWORD: {{.Values.ADMIN_POSTGRES_PASSWORD | quote}}