apiVersion: v1
kind: ConfigMap
metadata:
  name: yugabyte-db-init-scripts
  namespace: {{.Release.Namespace}}
data:
  init-yugabyte-db.sh: |
    #!/bin/bash
    set -e

    echo "Waiting for Yugabyte to be ready..."
    until psql -h yb-tserver-0.yb-tservers.payment.svc.cluster.local -p 5433 -U yugabyte -d yugabyte -c "select 1" > /dev/null 2>&1; do
      echo "Yugabyte is unavailable - sleeping 5s"
      sleep 5
    done
    echo "Yugabyte is up - executing init script..."

    echo "Creating payment_service user in Yugabyte..."
  
    psql -v ON_ERROR_STOP=1 -h yb-tserver-0.yb-tservers.payment.svc.cluster.local -p 5433 -U yugabyte -d yugabyte <<EOSQL
        DO \$\$
        BEGIN
            IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '$YUGABYTE_DB_PAYMENT_SERVICE_USERNAME') THEN
                CREATE USER "$YUGABYTE_DB_PAYMENT_SERVICE_USERNAME" WITH PASSWORD '$YUGABYTE_DB_PAYMENT_SERVICE_PASSWORD';
            END IF;
        END
        \$\$;

        GRANT ALL ON SCHEMA public TO "$YUGABYTE_DB_PAYMENT_SERVICE_USERNAME";
        GRANT CREATE ON SCHEMA public TO "$YUGABYTE_DB_PAYMENT_SERVICE_USERNAME";
        GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "$YUGABYTE_DB_PAYMENT_SERVICE_USERNAME";
        GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "$YUGABYTE_DB_PAYMENT_SERVICE_USERNAME";
    EOSQL

    echo "Creating duty user in Yugabyte..."
    psql -v ON_ERROR_STOP=1 -h yb-tserver-0.yb-tservers.payment.svc.cluster.local -p 5433 -U yugabyte -d yugabyte <<-EOSQL
        DO \$\$
        BEGIN
            IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '$YUGABYTE_DB_DUTY_USERNAME') THEN
                CREATE USER "$YUGABYTE_DB_DUTY_USERNAME" WITH PASSWORD '$YUGABYTE_DB_DUTY_PASSWORD';
            END IF;
        END
        \$\$;
    
        GRANT ALL ON SCHEMA public TO "$YUGABYTE_DB_DUTY_USERNAME";
        GRANT CREATE ON SCHEMA public TO "$YUGABYTE_DB_DUTY_USERNAME";
        GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "$YUGABYTE_DB_DUTY_USERNAME";
        GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "$YUGABYTE_DB_DUTY_USERNAME";
        GRANT "$YUGABYTE_DB_PAYMENT_SERVICE_USERNAME" TO "$YUGABYTE_DB_DUTY_USERNAME";
    EOSQL

    echo "Configuring default privileges for future tables..."
    psql -v ON_ERROR_STOP=1 -h yb-tserver-0.yb-tservers.payment.svc.cluster.local -p 5433 -U yugabyte -d yugabyte <<-EOSQL
        ALTER DEFAULT PRIVILEGES FOR ROLE "$YUGABYTE_DB_PAYMENT_SERVICE_USERNAME" IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO "$YUGABYTE_DB_DUTY_USERNAME";
        ALTER DEFAULT PRIVILEGES FOR ROLE "$YUGABYTE_DB_PAYMENT_SERVICE_USERNAME" IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO "$YUGABYTE_DB_DUTY_USERNAME";
    EOSQL

    echo "✅ Yugabyte DB initialized with all required users."
