apiVersion: batch/v1
kind: Job
metadata:
  name: yugabyte-db-init-job
  namespace: {{.Release.Namespace}}
spec:
  backoffLimit: 20
  template:
    spec:
      containers:
        - name: yugabyte-db-init
          image: postgres:15-alpine
          command: ["/bin/bash", "/scripts/init-yugabyte-db.sh"]
          envFrom:
            - secretRef:
                name: yugabyte-db-credentials
          volumeMounts:
            - name: init-scripts
              mountPath: /scripts
      restartPolicy: Never
      volumes:
        - name: init-scripts
          configMap:
            name: yugabyte-db-init-scripts
            defaultMode: 0755
