filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    processors:
      - add_docker_metadata: ~
    json.keys_under_root: true
    json.add_error_key: true
    json.message_key: message  # assumes your JSON logs include a "message" field

output.elasticsearch:
  hosts: [ "http://elasticsearch:9200" ]


setup.template.name: "ecommerce-logs"
setup.template.pattern: "ecommerce-logs-*"
setup.ilm.enabled: false
setup.dashboards.enabled: false
setup.template.enabled: true

setup.kibana:
  host: "http://kibana:5601"

logging.level: info
monitoring.enabled: true