filebeat.inputs:
  - type: log
    enabled: true
    json.keys_under_root: true
    json.add_error_key: true
    paths:
      - /app-logs/payment-service*.log


output.elasticsearch:
  hosts: [ "http://elasticsearch:9200" ]
  username: ""
  password: ""
  index: "payment-service-logs"  # ✅ Send logs to a raw index

setup.kibana:
  host: "http://kibana:5601"

# ⛔ Disable dashboards and ILM
setup.dashboards.enabled: false
setup.ilm.enabled: false           # ✅ Disables data streams + ILM
setup.template.enabled: true       # ✅ Still installs mappings
setup.template.name: "payment-service-logs"
setup.template.pattern: "payment-service-logs*"