filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    processors:
      - add_docker_metadata: ~
      - decode_json_fields:
          fields: [ "log", "message" ]  # Try both fields for compatibility
          target: ""
          overwrite_keys: true
          max_depth: 1
          process_array: false

output.elasticsearch:
  hosts: [ "http://elasticsearch:9200" ]


setup.template.name: "ecommerce-logs"
setup.template.pattern: "ecommerce-logs-*"
setup.ilm.enabled: true
setup.dashboards.enabled: true
setup.template.enabled: true

setup.kibana:
  host: "http://kibana:5601"

logging.level: info
monitoring.enabled: false