apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/keycloak
  - ../../../base/messaging
  - ../../../base/monitoring
  - ../../../base/observability
  - ../../../base/payment-db
  - ../../../base/payment-service
  - ../../../base/payment-consumers
  - secrets/keycloak-db-credentials.yaml
  - secrets/payment-db-credentials.yaml
  - secrets/kafka-credentials.yaml
  # add all secrets/configmaps here