package com.dogancaglar.paymentservice.domain.model.ledger

/**
 * JournalType
 *
 * Enumerates every category of double-entry journal entry that the
 * Mor-DC ledger engine can produce. Each type maps directly to a
 * factory method on [JournalEntry] companion object.
 *
 *  AUTH_HOLD:
 *      DR PSP_RECEIVABLE / CR AUTH_LIABILITY.
 *      Created by PspResultConsumer when a PaymentAuthorized event is processed.
 *      Records the authorization hold placed on the shopper's instrument.
 *
 *  CAPTURE:
 *      DR AUTH_LIABILITY / CR PSP_RECEIVABLE (clears the hold).
 *      DR PSP_RECEIVABLE / CR MERCHANT_GROSS_POOL (records the gross asset).
 *      Now named [captureGrossAsset] in the factory to reflect that 100% of the
 *      captured amount lands in the primary merchant's gross pool regardless
 *      of any split rules. Split distribution is a separate INTERNAL_TRANSFER.
 *
 *  INTERNAL_TRANSFER:
 *      DR MERCHANT_GROSS_POOL / CR <sub-seller BalanceAccountType account>.
 *      Generated by [JournalEntry.executeSubSellerSplit] for each split entry
 *      in a MARKETPLACE payment. These postings redistribute funds from the
 *      primary merchant's holding pool to individual sub-seller accounts.
 *      NEVER generated for DIRECT_MERCHANT payments.
 *
 *  REFUND:
 *      Reversal of a CAPTURE. Credits the shopper's account via PSP.
 *
 *  SETTLEMENT:
 *      Records funds received from the acquirer into the platform's cash account.
 *      Net of PSP scheme fees.
 *
 *  COMMISSION_FEE:
 *      Records the platform's commission charge against the merchant account.
 *
 *  PAYOUT:
 *      Records a payout disbursed from the platform's cash to a merchant/seller.
 *
 *  ADJUSTMENT:
 *      Corrective posting applied when a settlement DISCREPANCY is detected.
 */
enum class JournalType {
    AUTH_HOLD,
    CAPTURE,
    INTERNAL_TRANSFER,
    REFUND,
    SETTLEMENT,
    COMMISSION_FEE,
    PAYOUT,
    ADJUSTMENT
}