apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/payment-db

secretGenerator:
  - name: payment-db-credentials
    envs:
      - secrets/payment-db-credentials.env

generatorOptions:
  disableNameSuffixHash: true