detekt:
  excludes:
    - '**/build/**'
    - '**/target/**'
    - '**/.idea/**'
    - '**/*.iml'
    - '**/*.class'

config:
  validation: true
  warningsAsErrors: false
  checkExhaustiveness: false

processors:
  active: true
  exclude:
    - 'FunctionCountProcessor'
    - 'PropertyCountProcessor'
    - 'ClassCountProcessor'
    - 'PackageCountProcessor'

console-reports:
  active: true
  exclude:
    - 'ProjectStatisticsReport'

output-reports:
  active: true
  exclude: [ ]


  style:
    FunctionNaming:
      active: true
      severity: info       # ✅ Change from warning → info (less intrusive)
      functionPattern: '^[a-z][a-zA-Z0-9]*$'

  comments:
    UndocumentedPublicFunction:
      active: false