services:
  payment-service:
    labels:
      service: payment-service
      environment: test
    container_name: payment-service
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      JAVA_OPTS: -JAVA_TOOL_OPTIONS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.rmi.port=9010 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Duser.timezone=UTC
      SPRING_PROFILES_ACTIVE: docker
    #      SPRING_DATA_REDIS_URL: redis://redis:6379
    #      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8081:8080"  # Avoid collision with Kafka UI
      - "9010:9010"   # <-- add this for JMX
    networks:
      - messaging-net
      - payment-net
      - monitoring-net
      - auth-net

networks:
  messaging-net:
    external: true
  payment-net:
    external: true
  monitoring-net:
    external: true
  auth-net:
    external: true