services:
  payment-service:
    labels:
      service: payment-service
      environment: local
    container_name: payment-service
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_REDIS_URL: redis://redis:6379
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8081:8080"  # Avoid collision with Kafka UI
    networks:
      - messaging-net
      - payment-net

networks:
  messaging-net:
    external: true
  payment-net:
    external: true