app:
  instance-id: ${POD_NAME:${HOSTNAME:${random.value}}}
  payment-service:
    api-key: secretpaymentapikey12345

spring:
  datasource:
    url: ${SPRING_DATASOURCE_CENTRAL_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    redis:
      url: ${SPRING_DATA_REDIS_URL:redis://localhost:6379}

psp:
  refund:
    simulation:
      currentScenario: NORMAL
  capture:
    simulation:
      currentScenario: NORMAL


