server:
  port: 8080

  data:
    redis:
      lettuce:
        pool:
          max-active: 64
          max-idle: 64
          min-idle: 8
          max-wait: 2000ms
    # Only the url should be



mybatis:
  mapper-locations: classpath*:mapper/*.xml
management:
  endpoints:
    web:
      exposure:
        include: "prometheus,metrics,health"
  endpoint:
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5,0.95,0.99
    export:
      prometheus:
        enabled: true
    enable:
      all: false
      http.server.requests: true
      tomcat.threads: true
      hikaricp.connections: true
      hikaricp.connections.acquire: true
      outbox.event.backlog: true
      outbox.dispatched: true
      outbox.dispatcher.duration: true
      kafka.consumer.fetch.manager.records.lag: true
      kafka.producer.topic.record.send: true
      process.cpu.usage: true
      jvm.threads.live: true
      jvm.memory.used: true
      jvm.memory.max: true
      jvm.gc.pause: true
      scheduler.outbox.active.threads: true
      scheduler.outbox.pool.size.threads: true
      scheduler.outbox.queue.size: true
      kafka.consumer.fetch.manager.records.consumed: true
      kafka.consumer.fetch.manager.fetch.latency: true
      kafka.consumer.io.time: true
spring.jackson.time-zone: UTC
