server:
  port: 8080
spring:
  jpa.open-in-view: false
  kafka:
    properties:
      session:
        timeout:
          ms: 45000
    producer:
      value-serializer: com.dogancaglar.infrastructure.config.kafka.serialization.EventEnvelopeSerializer
      properties: #maybe change partition assignment strategy
        partition.assignment.strategy: org.apache.kafka.clients.consumer.CooperativeStickyAssignor
        spring.deserializer.value.delegate.class: com.dogancaglar.infrastructure.config.kafka.deserialization.EventEnvelopeDeserializer
  # Only the bootstrap-servers should be overridden in profiles
  datasource:
    hikari:
      maximum-pool-size: 40
      minimum-idle: 10
      connection-timeout: 3000
      idle-timeout: 600000
      max-lifetime: 1800000
  # Only the url, username, password should be overridden in profiles
  data:
    redis:
      lettuce:
        pool:
          max-active: 64
          max-idle: 64
          min-idle: 8
          max-wait: 2000ms
    # Only the url should be overridden in profiles

mybatis:
  mapper-locations: classpath*:com/dogancaglar/infrastructure/persistence/mapper/*.xml
management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health"
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    enable:
      http: false
      jvm: true
      kafka: true
      hikari: true
      executor: true
  health:
    probes:
      enabled: true
spring.jackson.time-zone: UTC
spring.jpa.properties.hibernate.jdbc.time_zone: UTC