app:
  cache:
    ttl-seconds: 3600  # 1 hour redis  TTL for PSP result cache
  payment-service:
    api-key: secretpaymentapikey12345

  kafka: # Kafka configuration for dynamic consumers
    dynamic-consumers:
      - id: payment-order-executor
        topic: payment_order_created_topic
        group-id: payment-order-created-consumer-group
        class-name: com.dogancaglar.consumers.PaymentOrderExecutor
        concurrency: 1

      - id: payment-retry-executor
        topic: payment_order_retry_request_topic
        group-id: payment-order-retry-consumer-group
        class-name: com.dogancaglar.consumers.PaymentOrderRetryCommandExecutor
        concurrency: 1

      - id: payment-status-check-executor-scheduler
        topic: payment_status_check_scheduler_topic
        group-id: payment-status-check-scheduler-consumer-group
        class-name: com.dogancaglar.consumers.ScheduledPaymentStatusCheckExecutor
        concurrency: 1

server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
      directory: /var/log/tomcat
      prefix: access_log
      suffix: .log
      pattern: '%h %l %u %t "%r" %s %b %D'
      buffered: true
spring:
  kafka:
    properties:
      security.protocol: SASL_PLAINTEXT
      sasl.mechanism: SCRAM-SHA-256
      sasl.jaas.config: ${SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG}
      client-id: ${CLIENT_ID:payment-consumers}
    bootstrap-servers: kafka.payment.svc.cluster.local:9092
  data:
    redis:
      url: redis://redis-master:6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
psp:
  simulation:
    currentScenario: NORMAL
    scenarios:
      NORMAL:
        timeouts:
          enabled: true
          probability: 1       # 1% of requests time out
        latency:
          fast:
            probability: 70    # 70% are fast (50–150ms)
            minMs: 50
            maxMs: 150
          moderate:
            probability: 25    # 25% are moderate (150–300ms)
            minMs: 150
            maxMs: 300
          slow:
            probability: 5     # 5% are slow (300–600ms)
            minMs: 300
            maxMs: 600
        response:
          successful: 80
          retryable: 15
          statusCheck: 0
          nonRetryable: 5
      PEAK:
        timeouts:
          enabled: true
          probability: 25      # 25% timeouts
        latency:
          fast:
            probability: 30    # 30% fast (250–500ms)
            minMs: 250
            maxMs: 500
          moderate:
            probability: 50    # 50% moderate (501–1500ms)
            minMs: 501
            maxMs: 1500
          slow:
            probability: 20    # 20% slow (1501–2500ms)
            minMs: 1501
            maxMs: 2500
        response:
          successful: 50
          retryable: 45
          statusCheck: 0
          nonRetryable: 5
      DEGRADED:
        timeouts:
          enabled: true
          probability: 30      # 30% timeouts
        latency:
          fast:
            probability: 20    # 20% fast (2000–2200ms)
            minMs: 2000
            maxMs: 2200
          moderate:
            probability: 20    # 20% moderate (2201–2600ms)
            minMs: 2201
            maxMs: 2600
          slow:
            probability: 60    # 60% slow (2601–2990ms)
            minMs: 2601
            maxMs: 2990
        response:
          successful: 50
          retryable: 40
          statusCheck: 0
          nonRetryable: 10
      BEST_PSP_EVER:
        timeouts:
          enabled: false
          probability: 0
        latency:
          fast:
            probability: 100   # 100% fast (1–2ms)
            minMs: 1
            maxMs: 2
          moderate:
            probability: 0
            minMs: 0
            maxMs: 0
          slow:
            probability: 0
            minMs: 0
            maxMs: 0
        response:
          successful: 100
          retryable: 0
          statusCheck: 0
          nonRetryable: 0
