app:
  instance-id: ${POD_NAME:${HOSTNAME:${random.value}}}
  payment-service:
    api-key: secretpaymentapikey12345

spring:
  datasource:
    url: ${SPRING_DATASOURCE_CENTRAL_URL}
    username: ${SPRING_DATASOURCE_USERNAME} # This will be injected from a Kubernetes Secret
    password: ${SPRING_DATASOURCE_PASSWORD}

  data:
    redis:
      url: redis://redis-master:6379

psp:
  refund:
    simulation:
      currentScenario: NORMAL
  capture:
    simulation:
      currentScenario: NORMAL
