server:
  port: 8080 # App will listen on port 8080 *inside* the container. Docker maps host port (e.g., 8081:8080) to this.
#bootstrap:
#  servers: kafka:9092
spring:
  kafka: #url for kafka in container-since this is used in docker-compose we use the service name
    bootstrap-servers: kafka:9092
  datasource:
    url: jdbc:postgresql://payment-db:5432/payment?options=-c%20timezone=UTC
    username: payment
    password: payment
  data:
    redis: #url for redis in container-since this is used in docker-compose we use the service name
      url: redis://redis:6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

