server:
  port: 8080
spring:
  kafka:
    properties:
      session:
        timeout:
          ms: 45000
    producer:
      value-serializer: com.dogancaglar.infrastructure.config.kafka.serialization.EventEnvelopeSerializer
      properties: #maybe change partition assignment strategy
        partition.assignment.strategy: org.apache.kafka.clients.consumer.CooperativeStickyAssignor
        spring.deserializer.value.delegate.class: com.dogancaglar.infrastructure.config.kafka.deserialization.EventEnvelopeDeserializer

  # Only the url, username, password should be overridden in profiles
  data:
    redis:
      lettuce:
        pool:
          max-active: 64
          max-idle: 64
          min-idle: 8
          max-wait: 2000ms
    # Only the url should be overridden in profiles

mybatis:
  mapper-locations: classpath*:com/dogancaglar/infrastructure/persistence/mapper/*.xml
management:
  endpoints:
    web:
      exposure:
        include: "prometheus,metrics,health"
  endpoint:
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5,0.95,0.99
    export:
      prometheus:
        enabled: true
    enable:
      all: false
      http.server.requests: true
      tomcat.threads: true
      hikaricp.connections: true
      hikaricp.connections.acquire: true
      outbox.event.backlog: true
      outbox.dispatched: true
      outbox.dispatcher.duration: true
      kafka.consumer.fetch.manager.records.lag: true
      kafka.producer.topic.record.send: true
      process.cpu.usage: true
      jvm.threads.live: true
      jvm.memory.used: true
      jvm.memory.max: true
      jvm.gc.pause: true
      scheduler.outbox.active.threads: true
      scheduler.outbox.pool.size.threads: true
      scheduler.outbox.queue.size: true
      kafka.consumer.fetch.manager.records.consumed: true
      kafka.consumer.fetch.manager.fetch.latency: true
      kafka.consumer.io.time: true
spring.jackson.time-zone: UTC
