server:
  port: 8080
spring:
  jpa.open-in-view: false
  kafka:
  # Only the bootstrap-servers should be overridden in profiles
  datasource:
  # Only the url, username, password should be overridden in profiles
  data:
    redis:
    # Only the url should be overridden in profiles

mybatis:
  mapper-locations: classpath*:mapper/*.xml
management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health"
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    enable:
      http: false
      jvm: true
      kafka: true
      hikari: true
      executor: true
  health:
    probes:
      enabled: true
