postgresql:
  auth:
    database: central-db
    existingSecret: central-db-credentials
    secretKeys:
      adminPasswordKey: CENTRAL_DB_POSTGRES_PASSWORD

  primary:
    extraEnvVarsSecret: central-db-credentials
    initdb:
      scriptsConfigMap: central-db-init-configmap

    resources:
      requests:
        cpu: 200m
        memory: 800Mi
      limits:
        memory: 800Mi

    extendedConfiguration: |-
      shared_buffers=256MB
      effective_cache_size=512MB
      work_mem=3MB
      maintenance_work_mem=64MB
      max_parallel_workers_per_gather=0
      max_parallel_workers=2
      max_worker_processes=2
      temp_file_limit=2GB
      max_connections=55
      fsync=on
      synchronous_commit=on

  metrics:
    enabled: true
    service:
      ports:
        metrics: 9187
    serviceMonitor:
      enabled: false
      namespace: "payment"
      interval: 10s
      labels:
        release: prometheus-stack

config:
  CENTRAL_DB_URL: "jdbc:postgresql://central-db-postgresql:5432/central-db?options=-c%20timezone=UTC"