PAYMENT_SERVICE_APP_DB_USER: ENC[AES256_GCM,data:CHIXIcFMGg==,iv:xVV6vKF2xxmfx6PN2l8rNhBFEcAo/PcpFv9wkmGnsio=,tag:khTbOp+HxnK1piGxnk0I/Q==,type:str]
PAYMENT_SERVICE_APP_DB_PASSWORD: ENC[AES256_GCM,data:52ONt9rAGQ==,iv:bKLWpHLs75MnTW3tlekxD/8bvm31fhhtLK/DJTROumo=,tag:taK5g+KOUXZvg5Jz48i+xw==,type:str]
PAYMENT_CONSUMERS_APP_DB_USER: ENC[AES256_GCM,data:4ScdGz/tEloPUJhnljduTA==,iv:ieaXKUUIA3ddFkW4h9nZo6sP38SyIG6XrdTYnzUFQjs=,tag:ZryvrZ3QZ5BYpHGL1Oo+cw==,type:str]
PAYMENT_CONSUMERS_APP_DB_PASSWORD: ENC[AES256_GCM,data:2ZxIWiMUbwEIsE3xjlvnjQ==,iv:vAxEG2QZuFPOyFq4hJuPGrCLhSlHZTKC0TPmqA1GizY=,tag:Afo+EcfYnnep+5YRTasxOw==,type:str]
ADMIN_POSTGRES_PASSWORD: ENC[AES256_GCM,data:YGIZ5J9DMUhMmfcviA==,iv:QadIEHMkv/fmL99fXGQWv9cKN2VOsEyWQ1WDyThKKrU=,tag:4PKQNmbNcYQCU6lglUtNVA==,type:str]
KAFKA_CLIENT_PASSWORD: ENC[AES256_GCM,data:BbSEWJIeADDt7g==,iv:zNhHeiVPYOGQC95OZ5vDV8zKKmZzuLT+VHX1Dz6HuzU=,tag:6cGMZN4Bch/FbPmXKX7ESA==,type:str]
sops:
    age:
        - recipient: age1yq5dsms95qcm2c6kc6khet5tx3kkzeaj4ccxd4y4q85zyjdf8fcsgvjd9w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdHA1MVBTMWQ1V2kwNzdO
            YUxTbzQ1T2RWaVZkMW5ETklCa1l0V2VKVWlBCkdKakVDZnhqS0FXRDRjTEFzSE9y
            dWd1ZnlEUXNhSVRHS1FLK1o3UUZIWFkKLS0tIEtaOFZDaDhyelpuWEZjSjQ1bkhY
            Mmlmby9uL2RwWUNzODhVVkQ0SHJHVGcKUgKsbBgf8Q1fSUq//sxBJCSTbgnGpbw5
            DGnR+w78gy04Byk6nXT+y79R7aQcGtNZTGBg8yb2iCB4xvzzs7S03Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-23T20:08:27Z"
    mac: ENC[AES256_GCM,data:WACvZTy1zrStgYqjZlBzrPfYEhdJRD9hcMcizbGhwPumejmHkDVIpr77/m4YXxRfbFfnZFx4rmelC41noh7bof4z9zIAYAHFFrF+y6LqBYDRZGwJTsX0F5zx6NCffPpbLXUO4tdI8HBnFSCDFurwCTFvkYBRlS48d+jQHHHZA80=,iv:7eYF8IqHjC74YYUhZmqXytiTKneElsgVTcIyZ8f2FYo=,tag:NLXOBuDX4lYnnSqTFnslvw==,type:str]
    encrypted_regex: .*
    version: 3.10.2
