apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-db
  namespace: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-db
  template:
    metadata:
      labels:
        app: payment-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: "payment"
            - name: POSTGRES_USER
              value: "payment"
            - name: POSTGRES_PASSWORD
              value: "payment"
            - name: POSTGRES_MAX_CONNECTIONS
              value: "200"
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          emptyDir: { } # Replace with PVC for prod