apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      volumes:
        - name: jfr
          persistentVolumeClaim:
            claimName: jfr-data-payment-service
      containers:
        - name: payment-service
          volumeMounts:
            - name: jfr
              mountPath: /var/log/jfr
          image: dcaglar1987/payment-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080  # REST API
            - containerPort: 9010  # JMX
          env:
            #            - name: PYROSCOPE_APPLICATION_NAME
            #              value: payment-service
            #            - name: PYROSCOPE_SERVER_ADDRESS
            #              value: http://pyroscope.payment.svc:4040
            #            - name: PYROSCOPE_PROFILER_EVENT
            #              value: lock    # or lock or alloc or wall
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:StartFlightRecording=name=payment-service,filename=/var/log/jfr/pay.jfr,maxage=30m,maxsize=250M,settings=profile,dumponexit=true -XX:FlightRecorderOptions=repository=/var/log/jfr"
            - name: DATA_SOURCE_NAME
              value: "postgresql://payment:payment@payment-db:5432/payment?sslmode=disable"
            - name: SPRING_PROFILES_ACTIVE
              value: "local"
            - name: SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              valueFrom:
                configMapKeyRef:
                  name: payment-app-config
                  key: KEYCLOAK_ISSUER_URL
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: payment-app-config
                  key: PAYMENT_DB_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: payment-db-credentials
                  key: PAYMENT_SERVICE_APP_DB_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-db-credentials
                  key: PAYMENT_SERVICE_APP_DB_PASSWORD
            - name: KAFKA_CLIENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-db-credentials
                  key: KAFKA_CLIENT_PASSWORD

          # Kdeleafka credentials (Secret)
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 120     # Wait 2 minutes before first liveness check
            periodSeconds: 30            # Check every 30 seconds
            timeoutSeconds: 5            # Wait up to 5 seconds for response
            failureThreshold: 6          # Allow up to 6 failures before killing pod

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 120     # Wait 2 minutes before first readiness check (match liveness for smoother rollout)
            periodSeconds: 15            # Check readiness every 15 seconds
            timeoutSeconds: 5            # Wait up to 5 seconds for response
            failureThreshold: 6
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "2Gi"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jfr-data-payment-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi