apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "payment-service.fullname" . }}
  labels:
    {{- include "payment-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "payment-service.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "payment-service.fullname" . }}
    spec:
      containers:
        - name: payment-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080   # REST API
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JAVA_TOOL_OPTIONS
              value: "{{ .Values.jvmOpts }}"
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ .Values.spring.profile }}"
            - name: SPRING_DATA_REDIS_URL
              value: redis://redis-master:6379
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka.payment.svc.cluster.local:9092
            - name: SPRING_KAFKA_ADMIN_AUTO_CREATE
              value: "true"
            - name: SPRING_KAFKA_ADMIN_FAIL_FAST
              value: "true"
            - name: SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              valueFrom:
                configMapKeyRef:
                  name: payment-app-config
                  key: KEYCLOAK_ISSUER_URL
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: payment-app-config
                  key: PAYMENT_DB_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: payment-db-credentials
                  key: PAYMENT_SERVICE_APP_DB_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-db-credentials
                  key: PAYMENT_SERVICE_APP_DB_PASSWORD
          livenessProbe:
            httpGet: {path: /actuator/health/liveness, port: 9000}
            initialDelaySeconds: 90
            timeoutSeconds: 10
            periodSeconds: 10
            failureThreshold: 6

          readinessProbe:
            httpGet: {path: /actuator/health/readiness, port: 9000}
            initialDelaySeconds: 90
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 6

          startupProbe:
            httpGet: {path: /actuator/health/liveness, port: 9000}
            initialDelaySeconds: 15
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 90
          resources:
            {{- toYaml .Values.resources | nindent 12 }}


