apiVersion: batch/v1
kind: Job
metadata:
  name: grant-app-db-privileges-job
  namespace: {{.Release.Namespace}}
  labels:
    app: grant-app-db-privileges-job
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: grant-privileges
          image: postgres:16-alpine
          env:
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: payment-app-config
                  key: DB_NAME
            - name: DB_ADMIN_USER
              value: postgres
            - name: DB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-db-credentials
                  key: ADMIN_POSTGRES_PASSWORD
            - name: SERVICE_USER
              valueFrom:
                secretKeyRef:
                  name: payment-db-credentials
                  key: PAYMENT_SERVICE_APP_DB_USER
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              until pg_isready -h payment-db-postgresql -U postgres -d "$DB_NAME"; do
                echo "Waiting for Postgres to be ready…"
                sleep 2
              done
              echo "
                GRANT ALL ON SCHEMA public TO \"${SERVICE_USER}\";
                GRANT CREATE ON SCHEMA public TO \"${SERVICE_USER}\";
                GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO \"${SERVICE_USER}\";
                GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO \"${SERVICE_USER}\";
              " > /tmp/grant-privileges.sql
              export PGPASSWORD="${DB_ADMIN_PASSWORD}"
              echo "Connecting to database… and running following script "
              echo "Contents of /tmp/grant-privileges.sql:"
              cat /tmp/grant-privileges.sql
              if ! psql -h payment-db-postgresql -U postgres -d $DB_NAME --set ON_ERROR_STOP=off -f /tmp/grant-privileges.sql; then
                echo "Error: psql command failed!"
                exit 1
              fi