# templates/servicemonitor.yaml
  {{- if .Values.serviceMonitor.enabled}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "payment-service.fullname" . }}
  labels:
    {{- include "payment-service.labels" . | nindent 4 }}
      {{- with .Values.serviceMonitor.labels }}
      {{- toYaml . | nindent 4 }}
      {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ include "payment-service.fullname" . }}   # must match Service.metadata.labels
  endpoints:
    - port: mgmt
      path: {{.Values.serviceMonitor.path | default "/actuator/prometheus"}}
      interval: {{.Values.serviceMonitor.interval | default "30s"}}
      scrapeTimeout: {{.Values.serviceMonitor.scrapeTimeout | default "10s"}}
      scheme: {{.Values.serviceMonitor.scheme | default "http"}}
  # optional: only needed if the Service is in another namespace than this SM
  # namespaceSelector:
  #   matchNames:
  #     - {{ .Release.Namespace }}
        {{- end }}