apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32081   # Always use this port locally!
  selector:
    app: payment-service