apiVersion: v1
kind: Service
metadata:
  name: {{ include "payment-service.fullname" . }}
  labels:
    app: {{ include "payment-service.fullname" . }}
     {{- include "payment-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: {{ include "payment-service.fullname" . }}
  ports:
    - name: {{.Values.service.portName | default "http"}}
      port: {{.Values.service.port | default 8080}}
      targetPort: {{.Values.service.portName | default "http"}}
      protocol: TCP
    - name: mgmt
      port: 9000
      targetPort: 9000
      protocol: TCP