apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "payment-service.fullname" . }}
  labels:
    {{- include "payment-service.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "payment-service.fullname" . }}-headless # <--- Must match the headless svc name
  updateStrategy:
    type: RollingUpdate
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "payment-service.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "payment-service.fullname" . }}
    spec:
      podManagementPolicy: Parallel
      serviceName: {{ include "payment-service.fullname" . }}-headless
      updateStrategy:
        type: RollingUpdate
        replicas: {{.Values.replicaCount}}
      containers:
        - name: payment-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080   # REST API
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JAVA_TOOL_OPTIONS
              value: "{{ .Values.jvmOpts }}"
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ .Values.spring.profile }}"
            - name: SPRING_DATA_REDIS_URL
              value: redis://redis-master:6379
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka.payment.svc.cluster.local:9092
            - name: SPRING_KAFKA_ADMIN_AUTO_CREATE
              value: "true"
            - name: SPRING_KAFKA_ADMIN_FAIL_FAST
              value: "true"
            - name: SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              valueFrom:
                configMapKeyRef:
                  name: payment-app-config
                  key: KEYCLOAK_ISSUER_URL
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: payment-app-config
                  key: PAYMENT_DB_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: payment-db-credentials
                  key: PAYMENT_SERVICE_APP_DB_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-db-credentials
                  key: PAYMENT_SERVICE_APP_DB_PASSWORD
          startupProbe:
            httpGet: {path: /actuator/health/liveness, port: 9000}
            initialDelaySeconds: 30 # Wait 30s before even checking (Java/Spring warm-up) assumption app starts arouind 60 but for safety we max at 90
            periodSeconds: 5
            failureThreshold: 12     # Total 90s (30 + 6*10). This covers your 60s startup + a 30s buffer.
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12}}
          readinessProbe:
            httpGet: {path: /actuator/health/readiness, port: 9000}
            initialDelaySeconds: 0   # Becomes active immediately after Startup success
            periodSeconds: 10
            failureThreshold: 3      # 30s to pull from Load Balancer
            timeoutSeconds: 5

          livenessProbe:
            httpGet: {path: /actuator/health/liveness, port: 9000}
            initialDelaySeconds: 0   # Becomes active immediately after Startup success
            periodSeconds: 15
            failureThreshold: 6      # 90s to restart pod (gives Readiness time to fail first)
            timeoutSeconds: 5



