apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  type: NodePort   # For local minikube; change to LoadBalancer for GKE etc
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30300
  selector:
    app: grafana