apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - prometheus-deployment.yaml
  - prometheus-service.yaml
  - prometheus-configmap.yaml
  - grafana-deployment.yaml
  - grafana-service.yaml
  - grafana-datasources-configmap.yaml
  - pyroscope-statefulset.yaml

