apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 30s
      evaluation_interval: 30s
    scrape_configs:
    
      - job_name: 'payment-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'payment-service:8080' ]
      - job_name: 'payment-consumers'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'payment-consumers:8080' ]
      - job_name: 'redis-exporter'
        static_configs:
          - targets: ['redis-exporter:9121']