server:
  port: 8081

spring:
  application:
    name: payment-edge-workers
  jackson:
    time-zone: UTC
  data:
    redis:
  liquibase:
    enabled: false

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.dogancaglar.common.db.entity
  type-handlers-package: com.dogancaglar.common.db.typehandler

management:
  server:
    port: 9001
  health:
    probes:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "prometheus,metrics,health"
  endpoint:
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      application: payment-edge-workers
    enable:
      all: false
      hikaricp.connections: true
      hikaricp.connections.acquire: true
      process.cpu.usage: true
      jvm.threads.live: true
      jvm.memory.used: true
      jvm.memory.max: true
      jvm.gc.pause: true
      outbox_dispatched_total: true
      outbox_dispatch_failed_total: true
      outbox_event_backlog: true
      outbox_dispatcher_duration: true
      local_outbox_backlog_size: true
    distribution:
      percentiles-histogram:
        outbox_dispatcher_duration: true
      percentiles:
        outbox_dispatcher_duration: 0.5,0.95,0.99
    export:
      prometheus:
        enabled: true



app:
  datasource:
    outbox:
      driver-class-name: org.postgresql.Driver
      pool-name: edge-outbox-pool
    maintenance:
      driver-class-name: org.postgresql.Driver
      pool-name: edge-maint-pool
    central:
      driver-class-name: org.postgresql.Driver
      pool-name: central-writer-pool
