{
 "title": "Un PRovisioned Payment Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "HTTP Latency Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket[2m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket[2m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket[2m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket[2m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "JVM Heap Space Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": " sum(rate(http_server_requests_seconds_count{status=~\"5..\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Consumer Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "max(kafka_consumer_fetch_manager_records_lag) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Request Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outbox Job Duration (avg & max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(outbox_job_duration_seconds_sum[2m]) / rate(outbox_job_duration_seconds_count[2m])",
     "legendFormat": "Average Duration (s)"
    },
    {
     "expr": "outbox_job_duration_seconds_max",
     "legendFormat": "Max Duration (s)"
    }
   ]
  },
  {
   "title": "Kafka Records Consumed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(kafka_consumer_fetch_manager_records_consumed_total[2m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Outbox Dispatch Delay Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "outbox_dispatch_delay_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Outbox Event Backlog",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": " outbox_event_backlog", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Live Threads",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvm_threads_live_threads", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "tomcat_threads_busy_threads{name=\"http-nio-8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Db active connections",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hikaricp_connections_active", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Outbox Batch Size",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "outbox_dispatch_batch_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Db Idle Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    { "expr": "hikaricp_connections_idle", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "App Up time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_uptime_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Redis Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    { "expr": "redis_connections", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GC Pauses (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=\"payment-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Db Pending Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    { "expr": "hikaricp_connections_pending", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP 4xx Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"4..\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Retry Queue Size",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_retry_zset_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Redis Command Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "targets": [
    {
     "expr": "rate(redis_commands_duration_seconds_count[2m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}