# ---- Image (Bitnami Legacy) ----
image:
  registry: docker.io
  repository: bitnamilegacy/postgresql
  tag: 16.4.0-debian-12-r0   # override at deploy if you prefer another existing legacy tag
  pullPolicy: IfNotPresent

postgresqlSharedPreloadLibraries: "pgaudit,pg_stat_statements"

auth:
  existingSecret: central-db-credentials
  secretKeys:
    adminPasswordKey: CENTRAL_DB_POSTGRES_PASSWORD





primary:
  extraEnvVarsSecret: central-db-credentials
  extraEnvVars:
    - name: CENTRAL_DB_NAME
      valueFrom:
        configMapKeyRef:
          name: payment-platform-config
          key: CENTRAL_DB_NAME
    - name: POSTGRES_DB
      valueFrom:
        configMapKeyRef:
          name: payment-platform-config
          key: CENTRAL_DB_NAME
    - name: CENTRAL_DB_PAYMENT_CONSUMERS_USERNAME
      valueFrom:
        secretKeyRef:
          name: central-db-credentials
          key: CENTRAL_DB_PAYMENT_CONSUMERS_USERNAME
    - name: CENTRAL_DB_PAYMENT_CONSUMERS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: central-db-credentials
          key: CENTRAL_DB_PAYMENT_CONSUMERS_PASSWORD
    - name: CENTRAL_DB_PAYMENT_CENTRAL_RELAY_USERNAME
      valueFrom:
        secretKeyRef:
          name: central-db-credentials
          key: CENTRAL_DB_PAYMENT_CENTRAL_RELAY_USERNAME
    - name: CENTRAL_DB_PAYMENT_CENTRAL_RELAY_PASSWORD
      valueFrom:
        secretKeyRef:
          name: central-db-credentials
          key: CENTRAL_DB_PAYMENT_CENTRAL_RELAY_PASSWORD
    - name: CENTRAL_DB_PAYMENT_EDGE_WORKERS_USERNAME
      valueFrom:
        secretKeyRef:
          name: central-db-credentials
          key: CENTRAL_DB_PAYMENT_EDGE_WORKERS_USERNAME
    - name: CENTRAL_DB_PAYMENT_EDGE_WORKERS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: central-db-credentials
          key: CENTRAL_DB_PAYMENT_EDGE_WORKERS_PASSWORD
    - name: CENTRAL_DB_DUTY_USERNAME
      valueFrom:
        secretKeyRef:
          name: central-db-credentials
          key: CENTRAL_DB_DUTY_USERNAME
    - name: CENTRAL_DB_DUTY_PASSWORD
      valueFrom:
        secretKeyRef:
          name: central-db-credentials
          key: CENTRAL_DB_DUTY_PASSWORD
    - name: POSTGRES_USER
      value: postgres
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          name: central-db-credentials
          key: CENTRAL_DB_POSTGRES_PASSWORD
  initdb:
    scriptsConfigMap: central-db-init-scripts
  livenessProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 12
    successThreshold: 1

  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 6
    successThreshold: 1

  startupProbe:
    enabled: true
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 30

  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 768Mi

  extendedConfiguration: |
    # memory / caches
    shared_buffers = '256MB'               # ≈ 25% of 1Gi limit
    effective_cache_size = '512MB'         # OS page cache estimate
    work_mem = '3MB'                       # per sort/hash (per parallel op)
    maintenance_work_mem = '64MB'          # VACUUM/CREATE INDEX
    
    
    
    max_parallel_workers_per_gather = 0
    max_parallel_workers = 4
    max_worker_processes = 4
    
    temp_file_limit = '2GB'

    # connections (lower = less RAM)
    max_connections = 85

    # WAL / checkpoints
    fsync = on
    synchronous_commit = on

    # pg_stat_statements
    pg_stat_statements.max = 1000
    pg_stat_statements.track = top
    pg_stat_statements.track_utility = off
    pg_stat_statements.save = on

    # misc
    jit = off
    log_min_duration_statement = 1000
    log_statement = 'none'
    bgwriter_lru_maxpages = 400
    bgwriter_lru_multiplier = 2

metrics:
  enabled: false