# ingress-values.yaml
controller:
  service:
    type: LoadBalancer
    ports:
      http: 80
      https: 443
  resources:
    requests:
      cpu: 100m
      memory: 90Mi
    limits:
      cpu: 300m
      memory: 256Mi

  admissionWebhooks:
    patch:
      resources:
        requests:
          cpu: 20m
          memory: 32Mi
        limits:
          cpu: 100m
          memory: 64Mi
    createSecretJob:
      resources:
        requests:
          cpu: 20m
          memory: 32Mi
        limits:
          cpu: 100m
          memory: 64Mi