listeners:
  client:
    protocol: PLAINTEXT
    containerPort: 9092
    name: CLIENT
    sslClientAuth: ""
  controller:
    protocol: PLAINTEXT
    containerPort: 9093
    name: CONTROLLER
    sslClientAuth: ""
  interbroker:
    protocol: PLAINTEXT
    containerPort: 9094
    name: INTERNAL
    sslClientAuth: ""
  external:
    protocol: PLAINTEXT
    containerPort: 9095
    name: EXTERNAL
    sslClientAuth: ""
sasl:
  enabledMechanisms: ""
  interBrokerMechanism: ""
  controllerMechanism: ""
  interbroker:
    user: ""
    password: ""
  controller:
    replicaCount: 1
    user: ""
    password: ""
  client:
    users: []
    passwords: ""
  existingSecret: ""

replicaCount: 1



metrics:
  jmx:
    enabled: true                 # <- turn ON the JMX exporter container
  kafka:
    serviceMonitor:
      enabled: true
      namespace: payment
      labels:
        release: prometheus-stack

resources:
  requests:
    memory: 356Mi
    cpu: 500m
  limits:
    memory: 612Mi
    cpu: 1