kafkaServer:
  - kafka.payment.svc.cluster.local:9092

replicaCount: 1

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

service:
  type: ClusterIP
  port: 9308

prometheus:
  serviceMonitor:
    enabled: true
    namespace: "payment"              # ServiceMonitor lives in payment
    additionalLabels:
      release: prometheus-stack       # 👈 Prometheus will pick it up