auth:
  adminUser: admin
  adminPassword: adminpassword

proxy: edge

service:
  type: NodePort
  ports:
    http: 8080
  nodePorts:
    http: 32080

postgresql:
  enabled: true
  auth:
    username: bn_keycloak
    password: bitnami
    database: bitnami_keycloak
  service:
    ports:
      postgresql: 5434
  containerPorts:
    postgresql: 5434

resources:
  requests:
    memory: 700Mi
    cpu: 250m
  limits:
    memory: 1Gi
    cpu: 500m
livenessProbe:
  enabled: true
  initialDelaySeconds: 300    # generous warmup (was 120)
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

readinessProbe:
  enabled: true
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6