replicaCount: 1

postgresql:
  enabled: true
  auth:
    username: bn_keycloak
    password: bitnami
    database: bitnami_keycloak
  # leave ports at defaults (5432). Do NOT override.

service:
  type: NodePort
  ports:
    http: 8080
  nodePorts:
    http: 32080

# single-node cache; also blank out KC_CACHE_STACK so no jdbc-ping surprise
extraEnvVars:
  - name: KC_CACHE
    value: "local"
  - name: KC_CACHE_STACK
    value: "kubernetes"
  - name: KC_PROXY
    value: "edge"
  - name: KEYCLOAK_ADMIN
    value: "admin"
  - name: KEYCLOAK_ADMIN_PASSWORD
    value: "adminpassword"

resources:
  requests:
    memory: 500Mi
    cpu: 250m
  limits:
    memory: 768Mi
    cpu: 500m

livenessProbe:
  enabled: true
  initialDelaySeconds: 300
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

readinessProbe:
  enabled: true
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6