auth:
  adminUser: admin
  adminPassword: adminpassword

proxy: edge

service:
  type: NodePort
  ports:
    http: 8080
  nodePorts:
    http: 32080

postgresql:
  enabled: true
  auth:
    username: bn_keycloak
    password: bitnami
    database: bitnami_keycloak
  service:
    ports:
      postgresql: 5434
  containerPorts:
    postgresql: 5434
## Enable/Override Health Probes
livenessProbe:
  enabled: true
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
  path: /health/live
  scheme: HTTP

readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
  path: /health/ready
  scheme: HTTP

resources:
  requests:
    memory: 1Gi
    cpu: 250m
  limits:
    memory: 2Gi
    cpu: 1