
image:
  tag: "latest"
  pullPolicy: Always
  repository: dcaglar1987/payment-service




runPrivilegeGrantJob: true



service:
  type: ClusterIP
  port: 8080
  portName: http

serviceMonitor:
  enabled: true
  labels:
    release: prometheus-stack




spring:
  profile: local
