# Non-secret config
KEYCLOAK_ISSUER_URL: "http://keycloak:8080/realms/ecommerce-platform"
EDGE_DB_URL: "jdbc:postgresql://localhost:5432/edge-db?options=-c%20timezone=UTC"
CENTRAL_DB_URL: "jdbc:postgresql://central-db-postgresql:5432/central-db?options=-c%20timezone=UTC"
EDGE_DB_NAME: "edge-db"
CENTRAL_DB_NAME: "central-db"
YUGABYTE_DB_URL: "jdbc:postgresql://localhost:5433/yugabyte?options=-c%20timezone=UTC"