autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70
# image
image:
  repository: dcaglar1987/payment-service
  tag: latest
  pullPolicy: Always

# replica count
replicaCount: 1

runPrivilegeGrantJob: true

# JVM / JFR
jvmOpts: >-
  -XX:+UseZGC -Xms600m -Xmx600m

# Spring profile & datasource
spring:
  profile: local

# resources
resources:
  requests:
    cpu: 500m
    memory: 512Mi       # Safe lower bound for small pods
  limits:
    cpu: "2"
    memory: 1Gi

# PVC
persistence:
  enabled: true
  size: 2Gi
  accessMode: ReadWriteOnce