
redis:
  url: redis://redis-master:6379
kafka:
  bootstrapServers: kafka.payment.svc.cluster.local:9092
spring:
  profile: azure
serviceMonitor:
  enabled: false
  labels:
    release: prometheus-stack
  path: /actuator/prometheus
  interval: 30s
  scrapeTimeout: 10s
replicaCount: 1
keda:
  enabled: false
nodeSelector:
  pool: central
resources:
  requests: {cpu: "250m", memory: "512Mi"}
  limits: {cpu: "1000m", memory: "1024Mi"}
