image:
  tag: 16.3.0-debian-12-r12

postgresqlSharedPreloadLibraries: "pgaudit,pg_stat_statements"

auth:
  existingSecret: payment-db-credentials
  database: payment_db
  secretKeys:
    adminPasswordKey: ADMIN_POSTGRES_PASSWORD

primary:
  persistence:
    enabled: true
    size: 50Gi
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "1"
      memory: 2Gi
  extendedConfiguration: |
    checkpoint_timeout = '10min'
    max_wal_size = '4GB'
    min_wal_size = '512MB'
    checkpoint_completion_target = 0.9
    shared_buffers = '512MB'
    max_connections = 40
    pg_stat_statements.max = 1000
    pg_stat_statements.track = 'all'
    shared_preload_libraries = 'pgaudit,pg_stat_statements'
    log_min_duration_statement = 1000         # Log queries slower than 1s (in ms)
    log_statement = 'none'                    # (Optional, only logs queries by time not all)
    bgwriter_lru_maxpages = 400      # Try 200 or 400
    bgwriter_lru_multiplier = 2


metrics:
  enabled: true
  collectors:
    stat_statements: true
    long_running_transactions: true
  extraEnvVars:
    - name: PG_EXPORTER_FLAGS
      value: >
        --collector.stat_statements
        --collector.stat_statements.include_query
        --collector.stat_statements.limit=100
  serviceMonitor:
    enabled: true
    namespace: payment
    labels:
      release: prometheus-stack
