spring:
  profile: azure
image:
  repository: dcaglar1987/payment-consumers
  tag: latest
  pullPolicy: Always
resources:
  requests: {cpu: "150m", memory: "1024Mi"}
  limits:   {cpu: "1000m", memory: "2048Mi"}
jvmOpts: >-
  -XX:+UseG1GC -XX:+AlwaysActAsServerClassMachine -XX:+UseStringDeduplication
  -XX:MaxRAMPercentage=60 -XX:InitialRAMPercentage=60
  -XX:MaxMetaspaceSize=128m -XX:MaxDirectMemorySize=128m
  -XX:ThreadStackSize=512 -XX:MaxGCPauseMillis=200 -XX:InitiatingHeapOccupancyPercent=30
service:
  type: ClusterIP
  portName: http
  port: 8080
keda:
  enabled: true
  minReplicaCount: 1
  maxReplicaCount: 6
  pollingInterval: 15
  cooldownPeriod: 300
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: kafka.payment.svc.cluster.local:9092
        consumerGroup: psp-capture-executor-consumer-group
        topic: gateway.capture.commands
        lagThreshold: "2400"
    - type: kafka
      metadata:
        bootstrapServers: kafka.payment.svc.cluster.local:9092
        consumerGroup: psp-refund-executor-consumer-group
        topic: gateway.refund.commands
        lagThreshold: "2400"
    - type: kafka
      metadata:
        bootstrapServers: kafka.payment.svc.cluster.local:9092
        consumerGroup: psp-result-consumer-group
        topic: payment.psp.results
        lagThreshold: "2400"
serviceMonitor:
  enabled: false
  path: /actuator/prometheus
  interval: 15s
  scrapeTimeout: 10s
  scheme: http
  labels:
    release: prometheus-stack
replicaCount: 1
nodeSelector:
  pool: central

redis:
  url: redis://redis-master:6379
kafka:
  bootstrapServers: kafka.payment.svc.cluster.local:9092
