image:
  tag: 16.3.0-debian-12-r12

postgresqlSharedPreloadLibraries: "pgaudit,pg_stat_statements"

auth:
  existingSecret: payment-db-credentials
  database: payment_db
  secretKeys:
    adminPasswordKey: ADMIN_POSTGRES_PASSWORD
primary:
  livenessProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 12
    successThreshold: 1

  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 6
    successThreshold: 1

  startupProbe:
    enabled: true
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 30
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 800m
      memory: 1Gi
  extendedConfiguration: |
    # memory / caches
    shared_buffers = '256MB'               # ≈ 25% of 1Gi limit
    effective_cache_size = '512MB'         # OS page cache estimate
    work_mem = '4MB'                       # per sort/hash (per parallel op)
    maintenance_work_mem = '64MB'          # VACUUM/CREATE INDEX

    # connections (lower = less RAM)
    max_connections = 57

    # WAL / checkpoints (lighter on disk/CPU)
    checkpoint_timeout = '10min'
    max_wal_size = '1GB'
    min_wal_size = '256MB'
    checkpoint_completion_target = 0.9
    wal_compression = on

    # pg_stat_statements
    pg_stat_statements.max = 1000
    pg_stat_statements.track = top
    pg_stat_statements.track_utility = off
    pg_stat_statements.save = on

    # misc
    jit = off
    log_min_duration_statement = 1000
    log_statement = 'none'
    bgwriter_lru_maxpages = 400
    bgwriter_lru_multiplier = 2

metrics:
  enabled: false