# infra/helm-values/redis-values-local.yaml
architecture: standalone

auth:
  enabled: false

image:
  registry: docker.io
  repository: bitnamisecure/redis
  tag: latest
  pullPolicy: IfNotPresent

master:
  resources:
    requests:
      cpu: "200m"
      memory: "128Mi"
    limits:
      cpu: "1000m"
      memory: "512Mi"   # keep this if 1Gi isn't possible today
  # Probes: give Redis time when busy
  startupProbe:
    enabled: true
    periodSeconds: 5
    timeoutSeconds: 5
    failureThreshold: 90     # ~7.5 min (cold start / disk busy)
  readinessProbe:
    periodSeconds: 5
    timeoutSeconds: 10
    failureThreshold: 12     # ~1 min
  livenessProbe:
    periodSeconds: 5
    timeoutSeconds: 10
    failureThreshold: 12

  # Keep Redis lightweight in local dev: no persistence, bounded memory
  extraFlags:
    - "--save ''"                 # disable RDB snapshots
    - "--appendonly no"           # disable AOF
    - "--maxmemory 380mb"         # safely below 512Mi limit
    - "--maxmemory-policy allkeys-lru"
    - "--tcp-keepalive 30"
    - "--io-threads 2"
    - "--io-threads-do-reads yes"
    - "--latency-tracking yes"

# Don’t load a ConfigMap to avoid conflicts
# master.existingConfigmap: <REMOVE THIS LINE>

global:
  security:
    allowInsecureImages: true

metrics:
  enabled: false

#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: redis-config
#  namespace: payment
#data:
#  redis.conf: |
#    save 900 1
#    save 300 10
#    save 60 10000
#
#    appendonly yes
#    appendfsync everysec