# infra/helm-values/redis-values-local.yaml
architecture: standalone

auth:
  enabled: false

image:
  registry: docker.io
  repository: bitnamisecure/redis
  tag: latest            # <- multi-arch, pullable
  pullPolicy: IfNotPresent

master:
  # comment this out if you don't actually have such a ConfigMap
  # existingConfigmap: redis-config
  resources:
    requests: { cpu: "50m",  memory: "64Mi" }
    limits:   { cpu: "300m", memory: "256Mi" }
  configuration: |-
    maxmemory 160mb
    maxmemory-policy allkeys-lru

  existingConfigmap: redis-config

global:
  security:
    allowInsecureImages: true
# TURN OFF metrics (and ServiceMonitor) to avoid pulling extra images
metrics:
  enabled: false

livenessProbe:
  enabled: true
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 6

readinessProbe:
  enabled: true
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

startupProbe:
  enabled: true
  periodSeconds: 10
  failureThreshold: 60