replicas:
  master: 1
  tserver: 1

# Used to tell TServers it's a single-node cluster
# so it doesn't wait for 3 nodes to form Raft quorum
conf:
  tserver:
    flags:
      replication_factor: 1

resource:
  master:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  tserver:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

storage:
  master:
    size: 2Gi
  tserver:
    size: 5Gi

metrics:
  enabled: false

preflight:
  skipUlimit: true
  skipBindToPort: true
