apiVersion: v1
kind: Secret
metadata:
  name: edge-worker-credentials
type: Opaque
stringData:
  CENTRAL_DB_PAYMENT_EDGE_WORKERS_USERNAME: {{ .Values.CENTRAL_DB_PAYMENT_EDGE_WORKERS_USERNAME }}
  CENTRAL_DB_PAYMENT_EDGE_WORKERS_PASSWORD: {{ .Values.CENTRAL_DB_PAYMENT_EDGE_WORKERS_PASSWORD }}
  EDGE_DB_PAYMENT_EDGE_WORKERS_USERNAME: {{.Values.EDGE_DB_PAYMENT_EDGE_WORKERS_USERNAME}}
  EDGE_DB_PAYMENT_EDGE_WORKERS_PASSWORD: {{.Values.EDGE_DB_PAYMENT_EDGE_WORKERS_PASSWORD}}
  EDGE_DB_DUTY_USERNAME: {{.Values.EDGE_DB_DUTY_USERNAME}}
  EDGE_DB_DUTY_PASSWORD: {{.Values.EDGE_DB_DUTY_PASSWORD}}



