apiVersion: v1
kind: Secret
metadata:
  name: payment-central-relay-job-credentials
type: Opaque
stringData:
  CENTRAL_DB_PAYMENT_CENTRAL_RELAY_USERNAME: {{ .Values.CENTRAL_DB_PAYMENT_CENTRAL_RELAY_USERNAME }}
  CENTRAL_DB_PAYMENT_CENTRAL_RELAY_PASSWORD: {{ .Values.CENTRAL_DB_PAYMENT_CENTRAL_RELAY_PASSWORD}}
  CENTRAL_DB_DUTY_USERNAME: {{ .Values.CENTRAL_DB_DUTY_USERNAME }}
  CENTRAL_DB_DUTY_PASSWORD: {{ .Values.CENTRAL_DB_DUTY_PASSWORD }}
