apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 4
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      initContainers:
        - name: wait-for-payment-db
          image: postgres:15
          command: [ 'sh', '-c', 'until pg_isready -h payment-db -p 5432 -U payment; do echo waiting for payment-db; sleep 2; done;' ]
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-db-credentials
                  key: POSTGRES_PASSWORD
      containers:
        - name: payment-service
          image: dcaglar1987/payment-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080  # REST API
            - containerPort: 9010  # JMX
          env:
            - name: JAVA_OPTS
              value: "-JAVA_TOOL_OPTIONS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.rmi.port=9010 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Duser.timezone=UTC"
            - name: SPRING_PROFILES_ACTIVE
              value: "local"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: payment-db-credentials
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-db-credentials
                  key: POSTGRES_PASSWORD
            - name: SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG
              valueFrom:
                secretKeyRef:
                  name: kafka-credentials
                  key: KAFKA_JAAS_CONFIG
          envFrom:
            - configMapRef:
                name: payment-service-config        # Non-secret config values (ConfigMap)
            - secretRef:
                name: payment-db-credentials       # DB credentials (Secret)
            - secretRef:
                name: kafka-credentials            # Kafka credentials (Secret)
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"