global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'redis'
    static_configs:
      - targets: [ 'redis_exporter:9121' ]
  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'payment-service:8080' ]
  - job_name: 'payment-consumers'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'payment-consumers:8080' ]

