  spring:
  profile: "local"
topologySpreadConstraints: []
runPrivilegeGrantJob: true
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: ContainerResource
      containerResource:
        name: cpu
        container: payment-edge-workers
        target:
          type: Utilization
          # Increased to 85% to avoid 'panic' scaling on noise
          averageUtilization: 85
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 15
      selectPolicy: Max
      policies:
        - type: Pods
          value: 1 # Add 1 pod at a time
          periodSeconds: 45 # Wait 45s between steps to allow JIT/warmup
    scaleDown:
      # "The Patience Window": Keep pods for 5 mins after load drops.
      # Prevents killing pods during small traffic dips.
      stabilizationWindowSeconds: 300
      selectPolicy: Max
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
paymentService:
  image:
    pullPolicy: Always
  jvmOpts: >-
    -XX:+UseG1GC -XX:+AlwaysActAsServerClassMachine -XX:+UseStringDeduplication -XX:MaxRAMPercentage=45 -XX:InitialRAMPercentage=45 -XX:MaxMetaspaceSize=128m -XX:MaxDirectMemorySize=128m -XX:ThreadStackSize=512 -XX:MaxGCPauseMillis=200 -XX:InitiatingHeapOccupancyPercent=30
  resources:
    requests:
      cpu: 150m
      memory: 768Mi
    limits:
      cpu: 1500m
      memory: 768Mi
edgeWorker:
  image:
    pullPolicy: Always
  resources:
    requests: {cpu: "250m", memory: "512Mi"}
    limits: {cpu: "500m", memory: "768Mi"}
  jvmOpts: >-
    -XX:+UseG1GC -XX:+AlwaysActAsServerClassMachine -XX:+UseStringDeduplication -XX:MaxRAMPercentage=45 -XX:InitialRAMPercentage=45 -XX:MaxMetaspaceSize=128m -XX:MaxDirectMemorySize=128m -XX:ThreadStackSize=512 -XX:MaxGCPauseMillis=200 -XX:InitiatingHeapOccupancyPercent=30
serviceMonitor:
  enabled: true
  path: /actuator/prometheus
  interval: 15s
  scrapeTimeout: 10s
  scheme: http
  labels:
    release: prometheus-stack
service:
  type: ClusterIP
  port: 8080
  portName: http
redis:
  url: redis://redis-master:6379
kafka:
  bootstrapServers: kafka.payment.svc.cluster.local:9092
postgresExporter:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi


config:
  KEYCLOAK_ISSUER_URL: "http://keycloak:8080/realms/ecommerce-platform"
  EDGE_DB_URL: "jdbc:postgresql://localhost:5432/edge-db?options=-c%20timezone=UTC"
  CENTRAL_DB_URL: "jdbc:postgresql://central-db-postgresql:5432/central-db?options=-c%20timezone=UTC"
  EDGE_DB_NAME: "edge-db"
  CENTRAL_DB_NAME: "central-db"
  YUGABYTE_DB_URL: "jdbc:postgresql://yb-tservers:5433/yugabyte?options=-c%20timezone=UTC"