mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dogancaglar.paymentservice.adapter.outbound.persistance.entity
  type-handlers-package: com.dogancaglar.paymentservice.adapter.outbound.persistance.mybatis.typehandler
spring.jackson.time-zone: UTC

logging:
  level:
    org.springframework.test.context: DEBUG
    org.springframework.boot.test.context: DEBUG\
    org.springframework.context.annotation: DEBUG
    org.springframework.beans.factory: DEBUG
    org.springframework: DEBUG
    org.mybatis: DEBUG