kafka:
  bootstrap-servers: kafka:9092
spring:
  kafka:
    consumer:
      heartbeat-interval: 3000
      session-timeout: 10000
      max-poll-interval: 300000
      enable-auto-commit: false
      properties:
        partition.assignment.strategy: org.apache.kafka.clients.consumer.CooperativeStickyAssignor
    listener:
      micrometer-enabled: true
  datasource:
    url: jdbc:postgresql://payment-db:5432/payment
    username: payment
    password: payment
    hikari:
      maximum-pool-size: 120
      minimum-idle: 25
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
server:
  port: 8080
  data:
    redis:
      timeout: 2000ms
      lettuce:
        pool:
        max-active: 8

        max-idle: 8
        min-idle: 0
        max-wait: -1ms
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/ecommerce-platform
metrics:
  tags:
    application: payment-service
logging:
  level:
    org.springframework.kafka.listener.DeadLetterPublishingRecoverer: DEBUG
    org.apache.kafka.clients.producer.ProducerConfig: DEBUG
    org.apache.kafka.clients.producer.KafkaProducer: DEBUG