app:
  instance-id: ${POD_NAME:${HOSTNAME:${random.value}}}
  payment-service:
    api-key: secretpaymentapikey12345
  datasource:
    web:
      jdbc-url: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    redis:
      url: ${SPRING_DATA_REDIS_URL:redis://localhost:6379}

stripe:
  api:
    api-key: ${STRIPE_API_KEY:sk_test_51ShA8HEAJKUKtoJwTALvrfMadP0eoKwyggnasHkqgY6y6jLoSjg9YqewkxiYrRw54TnZ7tVFX5Xreg3qaHm5wWAX00tupdpr6y}

psp:
  authorization:
    simulation:
      currentScenario: NORMAL
      scenarios:
        NORMAL:
          timeouts:
            enabled: true
            probability: 0
          latency:
            fast:
              probability: 0
              minMs: 100
              maxMs: 300
            moderate:
              probability: 100
              minMs: 300
              maxMs: 500
            slow:
              probability: 0
              minMs: 500
              maxMs: 900
          response:
            successful: 100
            retryable: 0
            statusCheck: 0
            nonRetryable: 0
  refund:
    simulation:
      currentScenario: NORMAL
  capture:
    simulation:
      currentScenario: NORMAL
