  apiVersion: v1
  kind: Secret
  metadata:
  name: central-hub-credentials
  type: Opaque
  stringData:
   {{- /* This dumps all values under .Values.secrets.data automatically */}}
     {{- toYaml .Values.secrets.data | nindent 2 }}

 ---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: central-hub-credentials
spec:
  secretStoreRef:
    name: local-k8s-store
    kind: SecretStore
  target:
    name: central-hub-credentials
  dataFrom:
    - extract:
        # Assuming your KV store has a secret object that contains all these keys
        key: central-hub-all-secrets
         {{- end }}
---
# 4. The ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: central-hub-config
  labels:
data:
  {{- }}
    {{- toYaml .Values.config | nindent 2 }}
