apiVersion: v1
kind: Service
metadata:
  name: {{ include "payment-consumers.fullname" . }}
  labels:
    app: {{ include "payment-consumers.fullname" . }}
    {{- include "payment-consumers.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: {{ include "payment-consumers.fullname" . }}
  ports:
    - name: {{ .Values.service.portName | default "http" }}
      port: {{ .Values.service.port | default 8080 }}
      targetPort: {{ .Values.service.portName | default "http" }}
      protocol: TCP