apiVersion: v1
kind: Service
metadata:
  name: payment-consumers
  labels:
    app: payment-consumers
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: payment-consumers
