apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "payment-consumers.fullname" . }}
  labels:
    {{- include "payment-consumers.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "payment-consumers.fullname" . }}
  podManagementPolicy: OrderedReady
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ include "payment-consumers.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "payment-consumers.fullname" . }}
        {{- include "payment-consumers.labels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 60
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - payment-central-relay
                topologyKey: "kubernetes.io/hostname"


      containers:
        - name: payment-consumers
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "{{ .Values.jvmOpts }}"
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ .Values.spring.profile }}"
            - name: SPRING_DATA_REDIS_URL
              value: redis://redis-master:6379
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka.payment.svc.cluster.local:9092
            - name: SPRING_DATASOURCE_URL
              valueFrom: { configMapKeyRef: { name: payment-platform-config, key: CENTRAL_DB_URL } }
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: central-db-credentials
                  key: CENTRAL_DB_PAYMENT_CONSUMERS_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: central-db-credentials
                  key: CENTRAL_DB_PAYMENT_CONSUMERS_PASSWORD
          startupProbe:
            httpGet: { path: /actuator/health/liveness, port: http }
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 60
          livenessProbe:
            httpGet: { path: /actuator/health/liveness, port: http }
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 12
          readinessProbe:
            httpGet: { path: /actuator/health/readiness, port: http }
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 12
          resources:
            {{- toYaml .Values.resources | nindent 12 }}