apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - consumer-auto-scaler.yaml
# Ingress is now managed in the overlay, not in the base.
