{
 "title": "Payment Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "HTTP Requests Per Second (/payments)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=\"/payments\", method=\"POST\"}[1m]))"
    }
   ]
  },
  {
   "title": "HTTP Latency Percentiles (p50/p95/p99)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{uri=\"/payments\"}[2m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{uri=\"/payments\"}[2m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{uri=\"/payments\"}[2m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Tomcat Thread Pool Utilizatioin %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "(\n  tomcat_threads_busy_threads{name=\"http-nio-8080\"}\n  /\n  tomcat_threads_config_max_threads{name=\"http-nio-8080\"}\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Success/Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"5..\", uri=\"/payments\"}[1m]))",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "DB Connection Pool Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(hikaricp_connections_active{job=\"payment-service\"}/hikaricp_connections_max{job=\"payment-service\"})*100",
     "legendFormat": "payment-service"
    },
    {
     "expr": "(hikaricp_connections_active{job=\"payment-consumers\"}/hikaricp_connections_max{job=\"payment-consumers\"})*100",
     "legendFormat": "payment-consumers"
    }
   ]
  },
  {
   "title": "DB Pool Pending Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 9 },
   "targets": [
    {
     "expr": "hikaricp_connections_pending{job=\"payment-service\"}",
     "legendFormat": "Payment Service"
    },
    {
     "expr": "hikaricp_connections_pending{job=\"payment-consumers\"}",
     "legendFormat": "Payment Consuemrs"
    }
   ]
  },
  {
   "title": "DB Acquire Time (max seconds)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "hikaricp_connections_acquire_seconds_max{job=\"payment-service\"}*1000",
     "legendFormat": "payment-service"
    },
    {
     "expr": "hikaricp_connections_acquire_seconds_max{job=\"payment-consumers\"}*1000",
     "legendFormat": "\"payment-consumers"
    }
   ]
  },
  {
   "title": "GC Pause (max ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(jvm_gc_pause_seconds_max{job=\"payment-service\"}) * 1000",
     "legendFormat": "payment-service"
    },
    {
     "expr": "max(jvm_gc_pause_seconds_max{job=\"payment-consumers\"}) * 1000",
     "legendFormat": "payment-consumers"
    }
   ]
  },
  {
   "title": "Outbox Event Backlog",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "outbox_event_backlog" }
   ]
  },
  {
   "title": "Successul Dispatached Outbox Event Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "rate(outbox_dispatched_total[1m])"
    }
   ]
  },
  {
   "title": "JVM Live Threads",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{job=\"payment-service\"}",
     "legendFormat": "payment-service"
    },
    {
     "expr": "jvm_threads_live_threads{job=\"payment-consumers\"}",
     "legendFormat": "payment-consumers"
    }
   ]
  },
  {
   "title": "Payment-Serviice-CPU Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 19, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"payment-service\"} * 100",
     "legendFormat": "payment-service"
    },
    {
     "expr": "process_cpu_usage{job=\"payment-consumers\"} * 100",
     "legendFormat": "payment-consumers"
    }
   ]
  },
  {
   "title": "Active Dispatcher Threads",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "scheduler_outbox_active_threads{name=\"outbox-dispatch\"}",
     "legendFormat": "Processed"
    }
   ]
  },
  {
   "title": "Dispatcher Task Pool Size",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 6, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scheduler_outbox_pool_size_threads{name=\"outbox-dispatch\"}",
     "legendFormat": "Pool Size"
    }
   ]
  },
  {
   "title": "JVM Heap Memory Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 13, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\"})/sum(jvm_memory_max_bytes{area=\"heap\"})*100"
    }
   ]
  },
  {
   "title": "Outbox Duration Per Thread",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(rate(outbox_dispatcher_duration_seconds_sum[1m]) / rate(outbox_dispatcher_duration_seconds_count[1m])) * 1000",
     "legendFormat": "Tasks in Queue"
    }
   ]
  },
  {
   "title": "Outbox Dispatacher Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 10, "y": 38 },
   "targets": [
    {
     "expr": "scheduler_outbox_queue_size{name=\"outbox-dispatch\"}",
     "legendFormat": "Active Threads"
    }
   ]
  },
  {
   "title": "Nr Of Total Outbox Message",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 38 },
   "targets": [
    { "expr": "outbox_dispatched_total", "legendFormat": "Outbox Batch Size" }
   ]
  },
  {
   "title": "Kafka Consumer Lag by Topic",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 4, "y": 48 },
   "targets": [
    {
     "expr": "max(kafka_consumer_fetch_manager_records_lag) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka Producer Sent Messages (by Topic)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 11, "y": 48 },
   "targets": [
    {
     "expr": "sum(rate(kafka_producer_topic_record_send_total[2m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka Records Consumed (by Topic)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 48 },
   "targets": [
    {
     "expr": "sum(rate(kafka_consumer_fetch_manager_records_consumed_total[2m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka Consumer Fetch Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "avg(kafka_consumer_fetch_manager_fetch_latency_avg) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka Consumer IO Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 5, "y": 59 },
   "targets": [
    {
     "expr": "(rate(kafka_consumer_io_time_ns_total[2m])/1e6)",
     "legendFormat": "IO Time (ms)"
    }
   ]
  },
  {
   "title": "Redis Total Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 11, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "redis_uptime_in_seconds", "legendFormat": "used, {{ instance }}" },
    {
     "expr": "redis_memory_max_bytes{instance=~\"$instance\"}",
     "legendFormat": "max, {{ instance }}"
    }
   ]
  },
  {
   "title": "Redis Clients",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_connected_clients" }
   ]
  },
  {
   "title": "Redis Expiring vs Not-Expiring Keys",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(redis_db_keys{instance=\"redis_exporter:9121\"}) by (instance)\n- \nsum(redis_db_keys_expiring{instance=\"redis_exporter:9121\"}) by (instance)",
     "legendFormat": "not expiring, {{ instance }}"
    },
    {
     "expr": "sum(redis_db_keys_expiring{instance=\"redis_exporter:9121\"}) by (instance)",
     "legendFormat": "expiring, {{ instance }}"
    }
   ]
  },
  {
   "title": "Redis Total Commands / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(redis_commands_total{instance=\"redis_exporter:9121\"}[1m])) by (cmd)",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Redis Hits / Misses per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total[1m])",
     "legendFormat": "hits, {{ instance }}"
    },
    {
     "expr": "irate(redis_keyspace_misses_total[1m])",
     "legendFormat": "misses, {{ instance }}"
    }
   ]
  },
  {
   "title": "Redis Expired/Evicted Keys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 10, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{instance=\"redis_exporter:9121\"}[1m])) by (instance)",
     "legendFormat": "expired, {{ instance }}"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{instance=\"redis_exporter:9121\"}[5m])) by (instance)",
     "legendFormat": "evicted, {{ instance }}"
    }
   ]
  },
  {
   "title": "Redis Retry Job Duration (s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 16, "y": 68 },
   "targets": [
    {
     "expr": "redis_retry_dispatch_execution_seconds_sum/redis_retry_dispatch_execution_seconds_count",
     "legendFormat": "Avg Duration"
    }
   ]
  },
  {
   "title": "Redis Retry Batch Size-(1000default)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 2, "x": 22, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_retry_batch_size", "legendFormat": "Redis Retry Batch" }
   ]
  }
 ]
}