{
 "title": "Payment Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "test_type",
    "label": "Test Type",
    "query": {
     "query": "label_values(k6_http_req_duration_p95,test_type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "k6 tests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "k6_http_req_duration_p95{test_type=\"$test_type\"}",
     "legendFormat": "k6_http_req_duration_p95-{{scenario}}"
    },
    {
     "expr": " k6_http_req_duration_max{test_type=\"$test_type\"}",
     "legendFormat": "k6_http_req_duration_max-{{scenario}}"
    },
    {
     "expr": " k6_http_req_blocked_p95{test_type=\"$test_type\"}",
     "legendFormat": "k6_http_req_blocked_p95-{{scenario}}"
    },
    {
     "expr": "k6_http_req_waiting_p95{test_type=\"$test_type\"} ",
     "legendFormat": "k6_http_req_waiting_p95-{{scenario}}"
    }
   ]
  },
  {
   "title": "HTTP Latency Percentiles (p50/p95/p99)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{uri=\"/api/v1/payments\"}[2m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{uri=\"/api/v1/payments\"}[2m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{uri=\"/api/v1/payments\"}[2m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Tomcat Thread Pool",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (pod, name) (\n  tomcat_threads_busy_threads{application=\"payment-service\", namespace=\"payment\"}\n)",
     "legendFormat": "tomcat-busy-{{pod}}"
    },
    {
     "expr": "max by (pod, name) (\n  tomcat_threads_current_threads{application=\"payment-service\", namespace=\"payment\"}\n)",
     "legendFormat": "tomcat-current-thread-{{pod}}"
    },
    {
     "expr": "max by (pod, name) (\n  tomcat_threads_config_max_threads{application=\"payment-service\", namespace=\"payment\"}\n)",
     "legendFormat": "tomcat-max-thread-{{pod}}"
    }
   ]
  },
  {
   "title": "http req suc/fail error rates",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 *\nsum(rate(http_server_requests_seconds_count{application=\"payment-service\",status=~\"2..\"}[1m]))\n/\nsum(rate(http_server_requests_seconds_count{application=\"payment-service\"}[1m]))",
     "legendFormat": "http-2xx rate"
    },
    {
     "expr": "100 *\nsum(rate(http_server_requests_seconds_count{application=\"payment-service\",status=~\"5..\"}[1m]))\n/\nsum(rate(http_server_requests_seconds_count{application=\"payment-service\"}[1m]))",
     "legendFormat": "http500xx errors"
    },
    {
     "expr": "100 *\nsum(rate(http_server_requests_seconds_count{application=\"payment-service\",status=~\"4..\"}[1m]))\n/\nsum(rate(http_server_requests_seconds_count{application=\"payment-service\"}[1m]))",
     "legendFormat": "http4xx rate"
    }
   ]
  },
  {
   "title": "HTTP Requests Per Second (/payments)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"payment-service\", uri=\"/api/v1/payments\", method=\"POST\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "load350_ramping_arrival_rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 6, "y": 10 },
   "targets": [
    {
     "expr": "k6_http_req_duration_p95{test_type=\"load350_ramping_arrival_rate\"}",
     "legendFormat": "k6_http_req_duration_p95"
    },
    {
     "expr": " k6_http_req_duration_max{test_type=\"load350_ramping_arrival_rate\"}",
     "legendFormat": "k6_http_req_duration_max"
    },
    {
     "expr": " k6_http_req_blocked_p95{test_type=\"load350_ramping_arrival_rate\"}",
     "legendFormat": "k6_http_req_blocked_p95"
    },
    {
     "expr": "k6_http_req_waiting_p95{test_type=\"load350_ramping_arrival_rate\"}",
     "legendFormat": "k6_http_req_waiting_p95"
    }
   ]
  },
  {
   "title": "load200_ramping_arrival_rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 10, "y": 10 },
   "targets": [
    {
     "expr": "sum(k6_http_req_duration_p95{test_type=\"load200_ramping_arrival_rate\"})",
     "legendFormat": "k6_http_req_duration_p95"
    },
    {
     "expr": "sum(k6_http_req_duration_max{test_type=\"load200_ramping_arrival_rate\"})",
     "legendFormat": "k6_http_req_duration_max"
    },
    {
     "expr": "sum(k6_http_req_blocked_p95{test_type=\"load200_ramping_arrival_rate\"})",
     "legendFormat": "k6_http_req_blocked_p95"
    },
    {
     "expr": "sum(k6_http_req_waiting_p95{test_type=\"load200_ramping_arrival_rate\"})",
     "legendFormat": "k6_http_req_waiting_p95"
    }
   ]
  },
  {
   "title": "k6 load250_ramping_arrival_rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 14, "y": 10 },
   "targets": [
    {
     "expr": "sum(k6_http_req_duration_p95{test_type=\"load250_ramping_arrival_rate\"})",
     "legendFormat": "k6_http_req_duration_p95"
    },
    {
     "expr": " sum(k6_http_req_duration_max{test_type=\"load250_ramping_arrival_rate\"})",
     "legendFormat": "k6_http_req_duration_max"
    },
    {
     "expr": " sum(k6_http_req_blocked_p95{test_type=\"load250_ramping_arrival_rate\"})",
     "legendFormat": "k6_http_req_blocked_p95"
    },
    {
     "expr": "sum(k6_http_req_waiting_p95{test_type=\"load250_ramping_arrival_rate\"})",
     "legendFormat": "k6_http_req_waiting_p95"
    }
   ]
  },
  {
   "title": "load300_ramping_arrival_rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 10 },
   "targets": [
    {
     "expr": "sum(k6_http_req_duration_p95{test_type=\"load300_ramping_arrival_rate\"})",
     "legendFormat": "k6_http_req_duration_p95"
    },
    {
     "expr": "sum(k6_http_req_duration_max{test_type=\"load300_ramping_arrival_rate\"})",
     "legendFormat": "k6_http_req_duration_max"
    },
    {
     "expr": "sum(k6_http_req_blocked_p95{test_type=\"load300_ramping_arrival_rate\"})",
     "legendFormat": "k6_http_req_blocked_p95"
    },
    {
     "expr": "sum(k6_http_req_waiting_p95{test_type=\"load300_ramping_arrival_rate\"})",
     "legendFormat": "k6_http_req_waiting_p95"
    }
   ]
  },
  {
   "title": "WEB DB Pool  Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (\n  hikaricp_connections_active{\n    application=\"payment-service\", pool=\"web-pool\"\n  }\n/\n  hikaricp_connections_max{\n    application=\"payment-service\", pool=\"web-pool\"\n  }\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "WEB DB Pool  Pending Connection",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 5, "x": 6, "y": 20 },
   "targets": [
    {
     "expr": "max by (pod, pool) (\n  hikaricp_connections_pending{\n    application=\"payment-service\",\n    namespace=\"payment\",\n    pool=\"web-pool\"\n  }\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "WEB DB Pool Acquire Time (max seconds)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 4, "x": 11, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by (pod) (\n  hikaricp_connections_acquire_seconds_max{application=\"payment-service\",pool=\"web-pool\"}\n) *1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "hikari-conn-timeout-total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(hikaricp_connections_timeout_total{application=\"payment-service\",pool=\"web-pool\"}[1m]) * 1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "WEB DB Pool-Avg Tx Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(rate(hikaricp_connections_usage_seconds_sum{application=\"payment-service\",pool=\"web-pool\"}[1m])\n/\nrate(hikaricp_connections_usage_seconds_count{application=\"payment-service\",pool=\"web-pool\"}[1m]))*1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JVM Heap Memory Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 5, "x": 15, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 *\nsum by (application, pod) (\n  jvm_memory_used_bytes{application=~\"payment-service\", area=\"heap\"}\n)\n/\nsum by (application, pod) (\n  jvm_memory_max_bytes{application=~\"payment-service\", area=\"heap\"}\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\n  100 *\n  sum by (application, pod) (\n    jvm_memory_used_bytes{application=~\"payment-service\", area=\"heap\"}\n  )\n  /\n  sum by (application, pod) (\n    jvm_memory_max_bytes{application=~\"payment-service\", area=\"heap\"}\n  )\n)\nand on (application, pod)\n(\n  100 *\n  sum by (application, pod) (\n    jvm_memory_used_bytes{application=~\"payment-service\", area=\"heap\"}\n  )\n  /\n  sum by (application, pod) (\n    jvm_memory_max_bytes{application=~\"payment-service\", area=\"heap\"}\n  ) > 60\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Pause (max ms)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 4, "x": 20, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": " max by (pod) (\n  max_over_time(jvm_gc_pause_seconds_max{application=\"payment-service\"}[5m])\n) *1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OutboxJob  DB Connection Pool Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (\n  hikaricp_connections_active{\n    application=\"payment-service\", pool=\"outbox-pool\"\n  }\n/\n  hikaricp_connections_max{\n    application=\"payment-service\", pool=\"outbox-pool\"\n  }\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "process_cpu_usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 5, "x": 6, "y": 31 },
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"payment-service\"} * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "jvm_threads_live_threads",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 4, "x": 11, "y": 31 },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{job=\"payment-service\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "PaymentConsumers  DB Connection Pool Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (\n  hikaricp_connections_active{\n    application=\"payment-consumers\", pool=\"HikariPool-1\"\n  }\n/\n  hikaricp_connections_max{\n    application=\"payment-consumers\", pool=\"HikariPool-1\"\n  }\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Outbox-DB Pool Pending Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 42 },
   "targets": [
    {
     "expr": "max by (pod, pool) (\n  hikaricp_connections_pending{\n    application=\"payment-service\",\n    namespace=\"payment\",\n    pool=\"outbox-pool\"\n  }\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "OutBoxJob DB Pool Acquire Time (max seconds)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by (pod) (\n  hikaricp_connections_acquire_seconds_max{application=\"payment-service\",pool=\"outbox-pool\"}\n) *1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "OutboxJobDB Pool-Avg Tx Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(rate(hikaricp_connections_usage_seconds_sum{application=\"payment-service\",pool=\"outbox-pool\"}[1m])\n/\nrate(hikaricp_connections_usage_seconds_count{application=\"payment-service\",pool=\"outbox-pool\"}[1m]))*1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "PaymentConsumers-DB Pool Pending Connections",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 52 },
   "targets": [
    {
     "expr": "max by (pod, pool) (\n  hikaricp_connections_pending{\n    application=\"payment-consumers\",\n    namespace=\"payment\",\n    pool=\"HikariPool-1\"\n  }\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "PaymentConsumers DB Pool Acquire Time (max seconds)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by (pod) (\n  hikaricp_connections_acquire_seconds_max{application=\"payment-consumers\",pool=\"HikariPool-1\"}\n) *1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "PaymentConsumers Pool-Avg Tx Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(rate(hikaricp_connections_usage_seconds_sum{application=\"payment-consumers\",pool=\"HikariPool-1\"}[1m])\n/\nrate(hikaricp_connections_usage_seconds_count{application=\"payment-consumers\",pool=\"HikariPool-1\"}[1m]))*1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "consumers-jvm_threads_live_threads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{job=\"payment-consumers\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Throughput (PSP calls/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(psp_calls_total{application=\"payment-consumers\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "consumers-process_cpu_usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 64 },
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"payment-consumers\"} * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Consumers-JVM Heap Memory Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 *\nsum by (application, pod) (\n  jvm_memory_used_bytes{application=~\"payment-consumers\", area=\"heap\"}\n)\n/\nsum by (application, pod) (\n  jvm_memory_max_bytes{application=~\"payment-consumers\", area=\"heap\"}\n)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "(\n  100 *\n  sum by (application, pod) (\n    jvm_memory_used_bytes{application=~\"payment-consumers\", area=\"heap\"}\n  )\n  /\n  sum by (application, pod) (\n    jvm_memory_max_bytes{application=~\"payment-consumers\", area=\"heap\"}\n  )\n)\nand on (application, pod)\n(\n  100 *\n  sum by (application, pod) (\n    jvm_memory_used_bytes{application=~\"payment-consumers\", area=\"heap\"}\n  )\n  /\n  sum by (application, pod) (\n    jvm_memory_max_bytes{application=~\"payment-consumers\", area=\"heap\"}\n  ) > 60\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Consumers-GC Pause (max ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by (pod) (\n  max_over_time(jvm_gc_pause_seconds_max{application=\"payment-consumers\"}[5m])\n) *1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outbox Event(OE) Processing Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "targets": [
    {
     "expr": "sum(rate(outbox_dispatched_total{application=\"payment-service\"}[$__rate_interval]))",
     "legendFormat": "Outbox Dispatch Rate(send publish kafka+set outbox to sent)"
    }
   ]
  },
  {
   "title": "Psp Exec Time Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 73 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le) (rate(psp_exec_duration_seconds_bucket{application=\"payment-consumers\"}[5m]))\n) * 1000",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (rate(psp_exec_duration_seconds_bucket{application=\"payment-consumers\"}[5m]))\n) * 1000",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le) (rate(psp_exec_duration_seconds_bucket{application=\"payment-consumers\"}[5m]))\n) * 1000",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Psp Queue Delay Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 73 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le) (rate(psp_queue_delay_seconds_bucket{application=\"payment-consumers\"}[5m]))\n) * 1000",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (rate(psp_queue_delay_seconds_bucket{application=\"payment-consumers\"}[5m]))\n) *1000",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le) (rate(psp_queue_delay_seconds_bucket{application=\"payment-consumers\"}[5m]))\n) *1000",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Outbox Batch Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 73 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (le) (rate(outbox_dispatcher_duration_seconds_bucket[$__rate_interval]))\n)",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (rate(outbox_dispatcher_duration_seconds_bucket[$__rate_interval]))\n)",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le) (rate(outbox_dispatcher_duration_seconds_bucket[$__rate_interval]))\n)",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "pspClient.charge() + kafkatx.run()",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le) (\n    rate(psp_call_latency_seconds_bucket{application=\"payment-consumers\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (\n    rate(psp_call_latency_seconds_bucket{application=\"payment-consumers\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le) (\n    rate(psp_call_latency_seconds_bucket{application=\"payment-consumers\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Outbox Event(OE) Backlog-OE Rows with NEW status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max without (instance, pod) (outbox_event_backlog{application=\"payment-service\"})",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Psp Response Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(psp_calls_total{application=\"payment-consumers\",result=\"SUCCESSFUL_FINAL\"}[2m]))\n/\nsum(rate(psp_calls_total{application=\"payment-consumers\"}[2m]))",
     "legendFormat": "Succesful"
    },
    {
     "expr": "sum(rate(psp_calls_total{application=\"payment-consumers\",result=\"FAILED_TRANSIENT_ERROR\"}[2m]))\n/\nsum(rate(psp_calls_total{application=\"payment-consumers\"}[2m]))",
     "legendFormat": "Failed(Transient)"
    },
    {
     "expr": "sum(rate(psp_calls_total{application=\"payment-consumers\",result=\"DECLINED_FINAL\"}[2m]))\n/\nsum(rate(psp_calls_total{application=\"payment-consumers\"}[2m]))",
     "legendFormat": "DECILINED-Final"
    },
    {
     "expr": "sum(rate(psp_calls_total{application=\"payment-consumers\",result=\"TIMEOUT\"}[2m]))\n/\nsum(rate(psp_calls_total{application=\"payment-consumers\"}[2m]))",
     "legendFormat": "Timeour-Transient"
    },
    {
     "expr": "sum(rate(psp_calls_total{application=\"payment-consumers\",result=\"INTERRUPTED\"}[2m]))\n/\nsum(rate(psp_calls_total{application=\"payment-consumers\"}[2m]))",
     "legendFormat": "InterruptedExceptipn"
    },
    {
     "expr": "sum(rate(psp_calls_total{application=\"payment-consumers\",result=\"EXCEPTION\"}[2m]))\n/\nsum(rate(psp_calls_total{application=\"payment-consumers\"}[2m]))",
     "legendFormat": "GenericException"
    }
   ]
  },
  {
   "title": "Lag by topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 82 },
   "targets": [
    {
     "expr": "sum by (topic, consumergroup) (\n  kafka_consumergroup_lag{consumergroup=\"payment-order-psp-call-executor-consumer-group\"}\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (topic, consumergroup) (\n  kafka_consumergroup_lag{consumergroup=\"payment-order-enqueuer-consumer-group\"}\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (topic, consumergroup) (\n  kafka_consumergroup_lag{consumergroup=\"payment-order-psp-result-updated-consumer-group\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer Throughut  per app/publisher/topic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "sum by (application, publisher, topic) (\n  label_replace(\n    rate(kafka_producer_topic_record_send_total[1m]),\n    \"publisher\", \"$1\", \"client_id\", \".*-(sync|batch)-payment-.*\"\n  )\n)",
     "legendFormat": "{{application}}-{{publisher}}-{{topic}}"
    }
   ]
  },
  {
   "title": "Producer-Request Latency per producer type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 90 },
   "targets": [
    {
     "expr": "avg by (application,ptype) (\n  label_replace(\n    kafka_producer_request_latency_avg,\n    \"ptype\", \"$1\",\n    \"client_id\", \".*-(sync|batch)-payment-.*\"\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Produce Rate Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 91 },
   "targets": [
    {
     "expr": "sum by (topic) (\n  rate(kafka_producer_topic_record_send_total[1m])\n)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "DQL offset By topic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 91 },
   "targets": [
    {
     "expr": "sum by (topic) (\n  max by (topic, partition) (\n    kafka_topic_partition_current_offset{\n      topic=~\"^payment.*\\\\.DLQ$\"\n    }\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer Throughut  Per deployment/type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 98 },
   "targets": [
    {
     "expr": "sum by (application, publisher) (\n  label_replace(\n    rate(kafka_producer_topic_record_send_total[1m]),\n    \"publisher\", \"$1\", \"client_id\", \".*-(sync|batch)-payment-.*\"\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer-Avg batch size per producer type",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 99 },
   "targets": [
    {
     "expr": "avg by (application,ptype) (\n  label_replace(\n    kafka_producer_batch_size_avg,\n    \"ptype\", \"$1\",\n    \"client_id\", \".*-(sync|batch)-payment-.*\"\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer Retry per producer type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 99 },
   "targets": [
    {
     "expr": "sum by (application, publisher) (\n  label_replace(\n    rate(kafka_producer_record_retry_total[1m]),\n    \"publisher\", \"$1\", \"client_id\", \".*-(sync|batch)-payment-.*\"\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer(Group) Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 100 },
   "targets": [
    {
     "expr": "sum by (consumergroup) (\n  rate(kafka_consumergroup_current_offset[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer Error per producer type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 106 },
   "targets": [
    {
     "expr": "sum by (application, publisher) (\n  label_replace(\n    rate(kafka_producer_record_error_total[1m]),\n    \"publisher\", \"$1\", \"client_id\", \".*-(sync|batch)-payment-.*\"\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Feth Latency per Ctype",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 107 },
   "targets": [
    {
     "expr": "avg by (ctype) (\n  label_replace(\n    kafka_consumer_fetch_manager_fetch_latency_avg,\n    \"ctype\", \"$1\",\n    \"client_id\", \"^(.*)-\\\\d+$\"\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer IO Time per Ctype(MS)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 108 },
   "targets": [
    {
     "expr": "avg by (ctype) (\n  label_replace(\n    kafka_consumer_io_time_ns_avg,\n    \"ctype\", \"$1\",\n    \"client_id\", \"^(.*)-\\\\d+$\"\n  )\n)/1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Rate Per Ctype",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 109 },
   "targets": [
    {
     "expr": "sum by (ctype, topic) (\n  label_replace(\n    rate(kafka_consumer_fetch_manager_records_consumed_total[1m]),\n    \"ctype\", \"$1\",\n    \"client_id\", \"^(.*)-\\\\d+$\"\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Retry Dispatcther Job-Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(redis_retry_events_total{result=\"processed\"}[$__rate_interval]))",
     "legendFormat": "Redit Retry PaymentOrderPsp"
    }
   ]
  },
  {
   "title": "Payment Retries Queue",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 117 },
   "targets": [
    {
     "expr": "sum(redis_retry_zset_size{application=\"payment-consumers\"})",
     "legendFormat": "Number of Scheduled Payment Retries"
    }
   ]
  }
 ]
}