apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# ...existing code...
resources:
  - ../../../base/payment-service


configMapGenerator:
  - name: payment-service-config
    envs:
      - config/payment-service-config.env
generatorOptions:
  disableNameSuffixHash: true