apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - redis-deployment.yaml
  - redis-service.yaml
  - redis-pvc.yaml
  - redis-exporter-deployment.yaml
  - kafka-statefulset.yaml
  - kafka-service.yaml
  - zookeeper-statefulset.yaml
  - zookeeper-service.yaml
