spring:
  profile: "azure"

keda:
  enabled: true
  minReplicaCount: 1
  maxReplicaCount: 2
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "85"
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 45
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15

paymentService:
  image:
    repository: dcaglar1987/payment-service
    tag: latest
    pullPolicy: Always
  jvmOpts: "-XX:+UseG1GC -XX:MaxRAMPercentage=60"
  resources:
    requests: {cpu: "1500m", memory: "2Gi"}
    limits: {cpu: "2500m", memory: "3Gi"}

redis:
  url: "redis://redis-master:6379"

ingress:
  enabled: true


config:
  KEYCLOAK_ISSUER_URL: "http://keycloak:8080/realms/ecommerce-platform"
  EDGE_DB_URL: "jdbc:postgresql://localhost:5432/edge-db?options=-c%20timezone=UTC"
  EDGE_DB_NAME: "edge-db"