spring:
  profile: "azure"

keda:
  enabled: false
  minReplicaCount: 1
  maxReplicaCount: 2
  pollingInterval: 15
  cooldownPeriod: 300
  triggers:
    - type: cpu # <--- Direct item in the array
      metricType: Utilization
      metadata:
        value: "85"
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 300
      selectPolicy: Max
      policies:
        - type: Pods
          value: 1 # Add 1 pod at a time
          periodSeconds: 45 # Wait 45s between steps to allow JIT/warmup
    scaleDown:
      # "The Patience Window": Keep pods for 5 mins after load drops.
      # Prevents killing pods during small traffic dips.
      stabilizationWindowSeconds: 300
      selectPolicy: Max
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15



paymentService:
  image:
    repository: dcaglar1987/payment-service
    tag: latest
    pullPolicy: Always
  jvmOpts: "-XX:+UseG1GC -XX:MaxRAMPercentage=60"
  resources:
    requests: {cpu: "1500m", memory: "2Gi"}
    limits: {cpu: "2500m", memory: "3Gi"}

redis:
  url: "redis://redis-master:6379"

ingress:
  enabled: true


config:
  KEYCLOAK_ISSUER_URL: "http://keycloak:8080/realms/ecommerce-platform"
  EDGE_DB_URL: "jdbc:postgresql://localhost:5432/edge-db?options=-c%20timezone=UTC"
  EDGE_DB_NAME: "edge-db"