apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  type: NodePort
  selector:
    app: keycloak
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32080   # You can pick a port in the 30000–32767 range, or let K8s assign
      protocol: TCP
