apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: edge-cell-global-store
spec:
  provider:
    azurekv:
      vaultUrl: "futurekeyvaulturl in cloud "
      auth:
        workloadIdentity:  #azure structuring