apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: payment
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      nodePort: 30000
  selector:
    app: payment-service
