apiVersion: v1
kind: Service
metadata:
  name: {{ include "central-db.fullname" . }}-headless # Standard name for headless
  labels:
    app: {{ include "central-db.fullname" . }}
spec:
  clusterIP: None # This is what makes it headless
  selector:
    app: {{ include "central-db.fullname" . }}
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
      protocol: TCP