# image
image:
  repository: dcaglar1987/payment-service
  tag: latest
  pullPolicy: Always

# replica count
replicaCount: 1



# Spring profile & datasource
spring:
  profile: local

runPrivilegeGrantJob: true
