# image
image:
  repository: dcaglar1987/payment-service
  tag: latest
  pullPolicy: Always

# replica count
replicaCount: 1

# JVM / JFR
jvmOpts: >-
  -XX:StartFlightRecording=name=payment-service,filename=/var/log/jfr/pay.jfr,maxage=30m,maxsize=250M,settings=profile,dumponexit=true
  -XX:FlightRecorderOptions=repository=/var/log/jfr

# Spring profile & datasource
spring:
  profile: local

# PVC
persistence:
  enabled: true
  size: 2Gi
  accessMode: ReadWriteOnce