EDGE_DB_PAYMENT_SERVICE_USERNAME: ENC[AES256_GCM,data:UdU0/vfaXF4PNXkDniLhZYhNpMud6n+tE72S0uNRfS4=,iv:ySfufWRnJBv5h6PHAgiQRnNs/9kP66loZCPcsNZIuYA=,tag:kuKGASrh0TGzkJoSAZGk1w==,type:str]
EDGE_DB_PAYMENT_SERVICE_PASSWORD: ENC[AES256_GCM,data:ffIlEaR+5lW/Q4MxGA2qX0e5IYQekgbqwr7ekj2YLYQ=,iv:fXuyGbOi/0LqmI5kqTjVwVVuVaBlzMcj3eGrjh0GoSQ=,tag:NIaRMCuL38YUpVhfCnCqQg==,type:str]
EDGE_DB_PAYMENT_EDGE_WORKERS_USERNAME: ENC[AES256_GCM,data:TUpl5YjTWvpbfMI8Mh4/q3jqWfPG6cP/b+LIBbP/eflIN2j41Q==,iv:tjmd72j8qSV/HH4gRznthUcrKrAyLmcJVJPRFLfefKE=,tag:ZkzrGS8qkXqP2HHbsBRQ6Q==,type:str]
EDGE_DB_PAYMENT_EDGE_WORKERS_PASSWORD: ENC[AES256_GCM,data:pkobey38R5xVfS1sS/GisqpVMJO8Cz7zfPt+2X9jlHPzslRIRQ==,iv:wVymHOa/ecxVeqbvG0McsZqTNkMpKDVmJg4Ish7k3nc=,tag:ElOOFiIFUTd7TYZVvzp+Cg==,type:str]
EDGE_DB_DUTY_USERNAME: ENC[AES256_GCM,data:ysjCzYKY3twJF1vuJPXg+RCVy/Zc,iv:z7xV3W59Cp/Zb7Du4i005dWMSwHwXgv3YCdrKDSsroE=,tag:9wXDJ7BBUmpnIM8q9afD8g==,type:str]
EDGE_DB_DUTY_PASSWORD: ENC[AES256_GCM,data:Dwqpt3zbuJ/1Yh/QsQBI1hrIyaqp,iv:NGul8XOPzOEhNcTHE+gCYBE//jrIxGl/v93aZWryniI=,tag:+iPbn+5037RVsIw42l1BZQ==,type:str]
EDGE_DB_POSTGRES_PASSWORD: ENC[AES256_GCM,data:6y+jZVXeJ5dUmpDnmZXWmnfZPpoF2NWMgw==,iv:ZcE22wjlqvTbDljhElPrMdP/C4Kc8Jso2pBToEOgb6Q=,tag:e/O8c5jw3kF0GuNOHLAmPQ==,type:str]
sops:
    age:
        - recipient: age1yq5dsms95qcm2c6kc6khet5tx3kkzeaj4ccxd4y4q85zyjdf8fcsgvjd9w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvUWhOZk4rdzVXUFl5WTlY
            YkhHRzJEbHFUMGpCU0Y4VWZqdHNGV3EvU1dRCnpYK0p3QjMxbmt2OFA3eWQ0UGZO
            Yy9GYlIyeWdMelpoV0VsTDNTVFZZaE0KLS0tIG4wTDY2OHAyVWFoVU9jSkp2YmJv
            dlVNODFwVHBDcmEyckVadE1jM2t1MmcKIAM5Ni4/8jO6Zy8XfTdqFncnX82C4YZv
            J7Z9YD1GbB1b6G3yZacR2sLKrYz5jlQbg9fA8L7tRjSucFPahEI+Kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T04:18:06Z"
    mac: ENC[AES256_GCM,data:dTWcpkxO1pIrXoWKXQq0xcTAftB7qZfjwEmK9UA/An+C7Ft0WkiY6c9Kg54D+kMIGU8YEpMxx3QPwNnzyNjRUhE8wvQhwiFpsul6tBxoSzN/naBscU1ORG9N4S+7bYX5dv8GMhso7eeVanPa6zmsKG6wHQTRjqt7Y7lWZkYsfek=,iv:6jTROa/SupUBbqiMGt2KVtm5kLvf5w4pZmaizIUX118=,tag:aIyNlwIcC5PGkOYsxadxiQ==,type:str]
    encrypted_regex: .*
    version: 3.10.2
