apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: payment
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      nodePort: 30002
  selector:
    app: redis