apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  type: NodePort  # For browser access in Minikube; change to ClusterIP with Ingress in prod
  ports:
    - port: 5601
      targetPort: 5601
      nodePort: 32561
  selector:
    app: kibana