resources:
  - filebeat-utils.yaml
  - filebeat-daemonset.yaml
  - filebeat-configmap.yaml
  - elasticsearch-statefulset.yaml
  - elasticsearch-pvc.yaml
  - elasticsearch-service.yaml
  - elasticsearch-headless-service.yaml
  - kibana-deployment.yaml
  - kibana-service.yaml
