apiVersion: v1
kind: Secret
metadata:
  name: edge-cell-credentials
type: Opaque
stringData:
  {{- /* Pluck only the Edge-related keys */}}
    {{- $edgeKeys := pick .Values "EDGE_DB_PAYMENT_SERVICE_USERNAME" "EDGE_DB_PAYMENT_SERVICE_PASSWORD" "EDGE_DB_PAYMENT_EDGE_WORKERS_USERNAME" "EDGE_DB_PAYMENT_EDGE_WORKERS_PASSWORD" "EDGE_DB_DUTY_USERNAME" "EDGE_DB_DUTY_PASSWORD" "EDGE_DB_POSTGRES_PASSWORD" }}
    {{- toYaml $edgeKeys | nindent 2 }}