{{- if .Values.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "payment-edge-cell.fullname" . }}
spec:
  scaleTargetRef:
    name: {{ include "payment-edge-cell.fullname" . }}
    kind: StatefulSet
  minReplicaCount: {{ .Values.keda.minReplicaCount }}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount }}
  triggers:
    {{- toYaml .Values.keda.triggers.metrics | nindent 4 }}
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        {{- toYaml .Values.keda.behavior | nindent 8 }}
  {{- end }}