
# 1. The Bridge Secret (Decrypted values from Helm)
{{- if eq .Values.secrets.storeName "local-k8s-store" }}
apiVersion: v1
kind: Secret
metadata:
  name: edge-cell-bridge-secret
type: Opaque
stringData:
  # Map your SOPS keys here so the SecretStore can see them
  EDGE_DB_PAYMENT_SERVICE_USERNAME: {{ .Values.EDGE_DB_PAYMENT_SERVICE_USERNAME | quote }}
  EDGE_DB_PAYMENT_SERVICE_PASSWORD: {{ .Values.EDGE_DB_PAYMENT_SERVICE_PASSWORD | quote }}
  EDGE_DB_PAYMENT_EDGE_WORKERS_USERNAME: {{ .Values.EDGE_DB_PAYMENT_EDGE_WORKERS_USERNAME | quote }}
  EDGE_DB_PAYMENT_EDGE_WORKERS_PASSWORD: {{ .Values.EDGE_DB_PAYMENT_EDGE_WORKERS_PASSWORD | quote }}
  EDGE_DB_DUTY_USERNAME: {{ .Values.EDGE_DB_DUTY_USERNAME | quote }}
  EDGE_DB_DUTY_PASSWORD: {{ .Values.EDGE_DB_DUTY_PASSWORD | quote }}
  EDGE_DB_POSTGRES_PASSWORD: {{ .Values.EDGE_DB_POSTGRES_PASSWORD | quote }}
  {{- end }}


---
#3 ExternalSecret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: edge-cell-credentials
spec:
  secretStoreRef:
    name: edge-cell-global-store
    kind: SecretStore
  target:
    name: edge-cell-credentials
  data:
    - secretKey: EDGE_DB_PAYMENT_SERVICE_USERNAME
      remoteRef:
        key: EDGE_DB_PAYMENT_SERVICE_USERNAME
    - secretKey: EDGE_DB_PAYMENT_SERVICE_PASSWORD
      remoteRef:
        key: EDGE_DB_PAYMENT_SERVICE_PASSWORD
    - secretKey: EDGE_DB_PAYMENT_EDGE_WORKERS_USERNAME
      remoteRef:
        key: EDGE_DB_PAYMENT_EDGE_WORKERS_USERNAME
    - secretKey: EDGE_DB_PAYMENT_EDGE_WORKERS_PASSWORD
      remoteRef:
        key: EDGE_DB_PAYMENT_EDGE_WORKERS_PASSWORD
    - secretKey: EDGE_DB_DUTY_USERNAME
      remoteRef:
        key: EDGE_DB_DUTY_USERNAME
    - secretKey: EDGE_DB_DUTY_PASSWORD
      remoteRef:
        key: EDGE_DB_DUTY_PASSWORD
    - secretKey: EDGE_DB_POSTGRES_PASSWORD
      remoteRef:
        key: EDGE_DB_POSTGRES_PASSWORD


---

# 4. The ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: edge-cell-config
data:
  # Using your exact keys
  KEYCLOAK_ISSUER_URL: {{ .Values.config.KEYCLOAK_ISSUER_URL | quote }}
  EDGE_DB_URL: {{ .Values.config.EDGE_DB_URL | quote }}
  CENTRAL_DB_URL: {{ .Values.config.CENTRAL_DB_URL | quote }}
  EDGE_DB_NAME: {{ .Values.config.EDGE_DB_NAME | quote }}
  CENTRAL_DB_NAME: {{ .Values.config.CENTRAL_DB_NAME | quote }}
  YUGABYTE_DB_URL: {{ .Values.config.YUGABYTE_DB_URL | quote }}
