  apiVersion: v1
  kind: Secret
  metadata:
  name: edge-cell-credentials
  type: Opaque
  stringData:
   {{- /* This dumps all values under .Values.secrets.data automatically */}}
     {{- toYaml .Values.secrets.data | nindent 2 }}

 ---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: edge-cell-credentials
spec:
  secretStoreRef:
    name: local-k8s-store
    kind: SecretStore
  target:
    name: edge-cell-credentials
  data:
    - secretKey: EDGE_DB_PAYMENT_SERVICE_USERNAME
      remoteRef:
        key: EDGE_DB_PAYMENT_SERVICE_USERNAME
    - secretKey: EDGE_DB_PAYMENT_SERVICE_PASSWORD
      remoteRef:
        key: EDGE_DB_PAYMENT_SERVICE_PASSWORD
    - secretKey: EDGE_DB_PAYMENT_EDGE_WORKERS_USERNAME
      remoteRef:
        key: EDGE_DB_PAYMENT_EDGE_WORKERS_USERNAME
    - secretKey: EDGE_DB_PAYMENT_EDGE_WORKERS_PASSWORD
      remoteRef:
        key: EDGE_DB_PAYMENT_EDGE_WORKERS_PASSWORD
    - secretKey: EDGE_DB_DUTY_USERNAME
      remoteRef:
        key: EDGE_DB_DUTY_USERNAME
    - secretKey: EDGE_DB_DUTY_PASSWORD
      remoteRef:
        key: EDGE_DB_DUTY_PASSWORD
    - secretKey: EDGE_DB_POSTGRES_PASSWORD
      remoteRef:
        key: EDGE_DB_POSTGRES_PASSWORD
---
# 4. The ConfigMap


apiVersion: v1
kind: ConfigMap
metadata:
  name: edge-cell-config
data:
  {{- toYaml .Values.config | nindent 2 }}