apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "payment-edge-cell.fullname" . }}
  labels:
    {{- include "payment-edge-cell.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "payment-edge-cell.fullname" . }}-headless
  updateStrategy:
    type: RollingUpdate
  replicas: {{ .Values.replicaCount }}
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: {{ include "payment-edge-cell.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "payment-edge-cell.fullname" . }}
      annotations:
        rollout/reboot: "{{ now | unixEpoch }}"
    spec:
      {{- if .Values.serviceAccount }}
      serviceAccountName: {{ .Values.serviceAccount.name | default "default" }}
      {{- end }}
      terminationGracePeriodSeconds: 120
      {{- if .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml .Values.topologySpreadConstraints | nindent 8 }}
      {{- end }}
      initContainers:
          ## we alsop remopbved central-db
        - name: edge-db
          image: postgres:15
          restartPolicy: Always   # <--- K8s 1.28
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            exec:
              command:
                - psql
                - -U
                - postgres
                - -d
                - edge-db
                - -tAc
                - "SELECT 1 FROM databasechangelog WHERE id = '20260208-optimize-idempotency-vacuum' AND author = 'dogancaglar' AND exectype = 'EXECUTED';"
          volumeMounts:
            - name: db-init-scripts
              mountPath: /docker-entrypoint-initdb.d
          envFrom:
            - secretRef:
                name: edge-cell-credentials
            - configMapRef:
                name: edge-cell-config
          env:
            - name: POSTGRES_DB
              valueFrom: {configMapKeyRef: {name: edge-cell-config, key: EDGE_DB_NAME}}
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom: {secretKeyRef: {name: edge-cell-credentials, key: EDGE_DB_POSTGRES_PASSWORD}}


        - name: liquibase-migration
          image: liquibase/liquibase:4.24.0 # <--- The official vanilla image
          env:
            - name: LIQUIBASE_COMMAND_URL
              valueFrom: {configMapKeyRef: {name: edge-cell-config, key: EDGE_DB_URL}}
            - name: LIQUIBASE_COMMAND_USERNAME
              valueFrom: {secretKeyRef: {name: edge-cell-credentials, key: EDGE_DB_PAYMENT_SERVICE_USERNAME}}
            - name: LIQUIBASE_COMMAND_PASSWORD
              valueFrom: {secretKeyRef: {name: edge-cell-credentials, key: EDGE_DB_PAYMENT_SERVICE_PASSWORD}}
          # Point Liquibase at the extracted files on the shared volume
          args: ["--search-path=/shared-workspace", "update", "--changelog-file=changelog.edge.xml"]
          volumeMounts:
            - name: liquibase-workspace
              mountPath: /shared-workspace
      containers:
        - name: payment-service
          image: "{{ .Values.paymentService.image.repository }}:{{ .Values.paymentService.image.tag }}"
          imagePullPolicy: {{.Values.paymentService.image.pullPolicy}}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: mgmt
              containerPort: 9000
              protocol: TCP
          envFrom:
            - secretRef:
                name: edge-cell-credentials
            - configMapRef:
                name: edge-cell-config
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JAVA_TOOL_OPTIONS
              value: "{{ .Values.paymentService.jvmOpts }}"
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ .Values.spring.profile }}"
            - name: SPRING_DATA_REDIS_URL
              value: "{{ .Values.redis.url }}"
            - name: EDGE_DB_NAME
              valueFrom: {configMapKeyRef: {name: edge-cell-config, key: EDGE_DB_NAME}}
            - name: EDGE_DB_URL
              valueFrom: {configMapKeyRef: {name: edge-cell-config, key: EDGE_DB_URL}}
            - name: EDGE_DB_PAYMENT_SERVICE_USERNAME
              valueFrom: {secretKeyRef: {name: edge-cell-credentials, key: EDGE_DB_PAYMENT_SERVICE_USERNAME}}
            - name: EDGE_DB_PAYMENT_SERVICE_PASSWORD
              valueFrom: {secretKeyRef: {name: edge-cell-credentials, key: EDGE_DB_PAYMENT_SERVICE_PASSWORD}}
            - name: SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              valueFrom: {configMapKeyRef: {name: edge-cell-config, key: KEYCLOAK_ISSUER_URL}}
      volumes:
        - name: db-init-scripts
          configMap:
            name: edge-db-init-configmap
        - name: liquibase-workspace
          configMap:
            name: edge-db-changelog-configmap