apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-provisioner
  namespace: auth
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: provisioner
          image: alpine:3.20
          command: [ "/bin/sh", "-c", "apk add --no-cache curl jq  && /scripts/provision-keycloak.sh" ]
          volumeMounts:
            - name: script
              mountPath: /scripts
            - name: output
              mountPath: /output
      volumes:
        - name: script
          configMap:
            name: keycloak-provision-script
            defaultMode: 0775
        - name: output
          hostPath:
            path: /Users/dogancaglar/IdeaProjects/ecommerce-platform-kotlin/keycloak/output
            type: DirectoryOrCreate
      restartPolicy: Never