apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "payment-edge-worker.fullname" . }}
spec:
  serviceName: payment-edge-worker-headless
  # ATTENTION: Using the same replicaCount to ensure 1-to-1 pairing with edge cells.
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: payment-edge-worker
  template:
    metadata:
      labels:
        app: payment-edge-worker
    spec:
      containers:
        # WORKER APPLICATION (Discovers its paired database over the network)
        - name: payment-edge-workers
          image: "{{ .Values.edgeWorker.image.repository }}:{{ .Values.edgeWorker.image.tag }}"
          env:
            # Retrieve the Pod name from K8s (e.g., payment-edge-worker-2)
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JAVA_TOOL_OPTIONS
              value: "{{ .Values.paymentService.jvmOpts }}"
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ .Values.spring.profile }}"
            - name: EDGE_DB_NAME
              valueFrom: {configMapKeyRef: {name: edge-cell-config, key: EDGE_DB_NAME}}
            - name: EDGE_CELL_BASE_URL
              value: "payment-edge-cell"
            - name: EDGE_CELL_HEADLESS_SERVICE
              value: "payment-edge-cell-headless"
            - name: EDGE_DB_PAYMENT_EDGE_WORKERS_USERNAME
              valueFrom: {secretKeyRef: {name: edge-cell-credentials, key: EDGE_DB_PAYMENT_EDGE_WORKERS_USERNAME}}
            - name: EDGE_DB_PAYMENT_EDGE_WORKERS_PASSWORD
              valueFrom: {secretKeyRef: {name: edge-cell-credentials, key: EDGE_DB_PAYMENT_EDGE_WORKERS_PASSWORD}}
              # Missing credentials for Maintenance pool
            - name: EDGE_DB_DUTY_USERNAME
              valueFrom: {secretKeyRef: {name: edge-cell-credentials, key: EDGE_DB_DUTY_USERNAME}}
            - name: EDGE_DB_DUTY_PASSWORD
              valueFrom: {secretKeyRef: {name: edge-cell-credentials, key: EDGE_DB_DUTY_PASSWORD}}
            - name: CENTRAL_DB_PAYMENT_EDGE_WORKERS_USERNAME
              valueFrom: {secretKeyRef: {name: edge-cell-credentials, key: CENTRAL_DB_PAYMENT_EDGE_WORKERS_USERNAME}}
            - name: CENTRAL_DB_PAYMENT_EDGE_WORKERS_PASSWORD
              valueFrom: {secretKeyRef: {name: edge-cell-credentials, key: CENTRAL_DB_PAYMENT_EDGE_WORKERS_PASSWORD}}
                # missing Central DB Config
            - name: CENTRAL_DB_URL
              valueFrom: {configMapKeyRef: {name: edge-cell-config, key: CENTRAL_DB_URL}}
            - name: CENTRAL_DB_PAYMENT_EDGE_WORKERS_USERNAME
              valueFrom: {secretKeyRef: {name: central-db-credentials, key: CENTRAL_DB_PAYMENT_EDGE_WORKERS_USERNAME}}
            - name: CENTRAL_DB_PAYMENT_EDGE_WORKERS_PASSWORD
              valueFrom: {secretKeyRef: {name: central-db-credentials, key: CENTRAL_DB_PAYMENT_EDGE_WORKERS_PASSWORD}}
          command: ["java", "-jar", "/app/app.jar"]
          ports:
            - name: http-worker
              containerPort: 8081
            - name: mgmt-worker
              containerPort: 9001
