apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/keycloak

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: keycloak-db-credentials
    envs:
      - secrets/keycloak-db-credentials.env