image:
  repository: dcaglar1987/payment-consumers
  tag: latest
  pullPolicy: Always



service:
  type: ClusterIP
  port: 8080
  portName: http

serviceMonitor:
  enabled: false
  path: /actuator/prometheus
  interval: 30s
  scrapeTimeout: 10s
  labels:
    release: prometheus-stack
